### ISSUE TITLE
Plane: EKF Altitude Runaway during RTK Fix

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#16791] opened 2021-03-03 00:41 UTC
## Bug report

**Issue details**

Altitude starts to run away prior to arming then constantly resets to 0 every few seconds. After arming, the altitude keeps increasing to ~1000m in maybe 30 seconds with the plane on the ground. Looks to be dangerous to fly, so we disarmed and called it a day.

**Version**
Plane Stable 4.0.9

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Twin motor electric

**Hardware type**
Cube Orange, Here2 (serial/i2c), Emlid Reach M2 (RTK).

**Logs**
https://1drv.ms/u/s!AunBK4rE1ZDCg_MahoKQUbxwQJ8o8w?e=vEWat9

**Comment by tridge** [comment] 2021-03-04 04:02
@Naterater thanks for this report! Could you try and reproduce this with ArduPilot master, and with the following key settings:
 - LOG_DISARMED=1
 - LOG_REPLAY=1
 - 
it needs to be master for the replay to be effective. If we got a replay log of this happening then we could very quickly fix it.

**Comment by peterbarker** [comment] 2021-03-04 04:10
@Naterater as an additional simple check - does this happen with *only* the RTK GPS attached?

**Comment by peterbarker** [comment] 2021-03-04 04:13
.... last time we looked at this it came down to bandwidth; does the same problem occur if you talk to the GPSs at 230400?

**Comment by tridge** [comment] 2021-03-04 04:23
a few notes:
 - First GPS is running at 10Hz, despite the config asking for 5Hz
 - 2nd GPS is running at the requested 5Hz (a u-blox M8)
 - EKF3 buffers will have been sized for reported lag for 1st GPS
 - main problem starts after it switches to the first GPS (the emlid reach)

**Comment by tridge** [comment] 2021-03-04 04:29
I think it is time we remove the buffer length code in EKF3 that depends on reported lag. We should use the max lag always, at least if we have more than 1 GPS configured

**Comment by tridge** [comment] 2021-03-04 05:45
@Naterater I think if you set GPS_DELAY_MS=120 and GPS_DELAY_MS2 to 120 then the problem would not happen
I will develop a PR to fix this, but first I will try to reproduce

**Comment by Naterater** [comment] 2021-03-04 05:48
I'll run some more tests ASAP. We did determine that it appears less likely linked to RTK as we had similar effects after losing RTK early on in the log. It still took about 45 minutes to start diverging though. Logs to follow.

**Comment by Naterater** [comment] 2021-03-04 05:50
And not that it makes too much of a difference, but we did already fix our update rates on our GPS units (10 and 5hz) for the Reach and Here respectively, but the problem still exists.

**Comment by tridge** [comment] 2021-03-04 06:41
> And not that it makes too much of a difference, but we did already fix our update rates on our GPS units (10 and 5hz) for the Reach and Here respectively, but the problem still exists.

it isn't the update rate that matters, it is the delay values

**Comment by Naterater** [comment] 2021-03-04 07:12
Log with the issue and replay enabled as suggested: https://1drv.ms/u/s!AunBK4rE1ZDCg_MeCKOBMYL9W4UIEQ?e=3b6oRq

Note that I can pretty reliably reproduce, and it only shows up after about 45 minutes.

**Comment by tridge** [comment] 2021-03-04 08:20
@Naterater brilliant! replay log replays correctly

**Comment by Naterater** [comment] 2021-03-04 18:40
For what it's worth, I can't seem to repeat the issue on 50Hz loop rate. I'm trying to get you a smaller log, but it's not happening.

**Comment by tridge** [comment] 2021-03-04 18:51
@Naterater did you get a log showing the issue when you had set both GPS_DELAY_MS and GPS_DELAY_MS2 to the same value? (a value of 120 would be suitable)

**Comment by Naterater** [comment] 2021-03-04 19:30
That log is here with each set to 120: https://1drv.ms/u/s!AunBK4rE1ZDCg_MnTod5RWyS_x8Fcg?e=bqQ4da

**Comment by Naterater** [comment] 2021-03-04 19:52
I couldn't get the altitude to show as crazy at 50Hz, so the log while reduced in rate is actually larger because we let it run for longer. https://1drv.ms/u/s!AunBK4rE1ZDCg_MsE_VcwiwTjl2QIw?e=8Psq1l

**Comment by WickedShell** [comment] 2021-03-04 20:22
> a few notes:
> 
>     * First GPS is running at 10Hz, despite the config asking for 5Hz
> 
>     * 2nd GPS is running at the requested 5Hz (a u-blox M8)

The GPS_RATE_MS parameter only applies to uBlox and apparently Allystar NMEA GPS units. Nothing else uses that, and we just cope with whatever we are handed.

**Comment by priseborough** [comment] 2021-03-05 01:24
The EKF is becoming over confident about its accuracy and the state variances collapse just prior to the divergence:

<img width="1032" alt="Screen Shot 2021-03-05 at 11 41 10 am" src="https://user-images.githubusercontent.com/3596952/110050348-d581dc00-7da7-11eb-98f3-894d1be3171d.png">

We have seen this type of behaviour in the past and this log has a number of factors that make it more likely, eg:

1) Lack of movement for extended periods.
2) Faster GPS update rates, eg 10Hz
3) Use of RTK GPS data with small reported error values
4) Use of RTK GPS for height

Reported GPS error levels from the primary GPS in use by both EKF instances including for height is small

<img width="1004" alt="Screen Shot 2021-03-05 at 12 15 22 pm" src="https://user-images.githubusercontent.com/3596952/110052899-78d4f000-7dac-11eb-84d5-d77741f12030.png">
<img width="1008" alt="Screen Shot 2021-03-05 at 12 15 40 pm" src="https://user-images.githubusercontent.com/3596952/110052920-825e5800-7dac-11eb-9b33-253893b6e921.png">

The next step is to come up with recommended tuning values for 10Hz operation with RTK GPS accuracy, but in the meantime, running the GPS updates at 5Hz would help. It may be necessary with 10Hz operation to limit the observation accuracy used by the horizontal position and height fusion to a minimum of 0.1m instead of the the current hardcoded lower limit of 0.05m.

**Comment by tridge** [comment] 2021-03-05 01:56
>  It may be necessary with 10Hz operation to limit the observation accuracy used by the horizontal position and height fusion to a minimum of 0.1m instead of the the current hardcoded lower limit of 0.05m.

do you mean gpsHgtAccuracy ? That has a lower limit of 1.5 * frontend->_gpsHorizPosNoise, which is 0.75 for this log.

**Comment by tridge** [comment] 2021-03-05 02:04
should we constrain the variances to a min value when inFlight is false?

**Comment by Naterater** [comment] 2021-03-05 02:33
I know that this "divergence" has happened without RTK FIX though. I'm trying to see if I've posted the log yet, but I had one without replay enabled unfortunately. Full disclosure, my recollection is that we did have RTK FIX for about 5-10 minutes during the first 15 minutes of the test, however it lost RTK FIX and degraded to just 3D Fix. 30 minutes later we saw the divergence.

**Comment by priseborough** [comment] 2021-03-05 04:21
The bad news is that neither increasing the minimum observation uncertainty to 0.5m and/or dropping GPS rate to 5Hz was effective on replay. The investigation continues.

**Comment by priseborough** [comment] 2021-03-06 06:22
Correction to my last update. Halving  the GPS measurement rate to 5Hz during replay does fix the divergence, eg:

<img width="1019" alt="Screen Shot 2021-03-06 at 5 20 59 pm" src="https://user-images.githubusercontent.com/3596952/110197543-58865d80-7ea0-11eb-9286-dc0a244c4c34.png">

The root cause still needs to be investigated and understood.

**Comment by priseborough** [comment] 2021-03-06 06:25
@Naterater Do you have the ability to reduce the output rate of your GPS to 5Hz?

**Comment by Naterater** [comment] 2021-03-06 13:43
@priseborough we do but we don’t. This GPS is also functioning as a precision logger for PPK, and 5Hz reduces our accuracy on turbulent days.

**Comment by priseborough** [comment] 2021-03-08 01:31
See https://github.com/ArduPilot/ardupilot/pull/16842 which fixes this issue on replay.

**Comment by tridge** [comment] 2021-03-08 06:10
@Naterater can you please test this firmware:
http://uav.tridgell.net/tmp/plane-CubeOrange-ekf3-test1.apj
that has the fixes from Pauls PR #16842 
please test with replay enabled. Thanks!

**Comment by Notorious811** [comment] 2021-03-11 10:34
@tridge @priseborough https://discuss.ardupilot.org/t/altitude-estimation-failure/67813/13, it seems like my issue is similar to this, keeping the quadcopter on for longer periods on ground without any movements make the EKF velocity, position and altitude estimations go haywire, should i try to backport this PR https://github.com/ArduPilot/ardupilot/pull/16842 onto the ArduCopter v4.0.4 which i am using currently and do some more tests?

**Comment by priseborough** [comment] 2021-03-26 10:18
Please check that the merge of https://github.com/ArduPilot/ardupilot/pull/16842 has resolved your issue.

**Comment by Notorious811** [comment] 2021-03-27 15:31
Yes, #16842 have resolved this issue for me, I also closed some of my previous issues which was directly related to this issue, seems alright to close this issue as well

**Closed** 2021-03-29 01:02 UTC
Labels: BUG, EKF

**Comment by rmackay9** [comment] 2021-03-29 01:05
Ah, I see @Naterater created this issue so perhaps I closed it prematurely.

I think it will be quite hard to backport this fix to Plane 4.0.x (which is similar to Copter-4.0.x) because there have been so many EKF3 changes since then so it will probably be best to test with "latest" if that's possible.  Of course as you know "latest" hasn't gone through beta testing so there is a higher chance of other issues/bugs.
