### ISSUE TITLE
Camera Trigger - add 3 positions support.

### ISSUE THREAD

**Issue by sashan13** [ArduPilot/ardupilot#6907] opened 2017-09-06 07:38 UTC
#### Issue details
So, I've got myself a nice trigger module that supports dozens of cameras. I use it for Sony a7. It has 2 inputs for triggering, one triggers photo when high, starts/stops video when low, does nothing at 1.5ms.  

Second one is 3 positions, akin to camera's hardware trigger button. Low state is normal, put it to mid, camera focuses, high - take photo.   The problem is, if I give this channel to Ardupilot it doesn't work since camera won't take photo when Ardupilot jumps from lowest to highest position while skipping the middle one. If I give first channel to Ardupilot I lose ability to record videos.

I propose adding option of 2 stage trigger. Add two more parameters, like CAM_MID_DURATION and CAM_SERVO_MID.
#### Version
3.5.2
#### Platform
[  ] All
[  ] AntennaTracker
[x] Copter
[x] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Any

#### Hardware type
Pixhack

#### Logs
No logs

**Comment by geofrancis** [comment] 2017-09-06 09:38
related to https://github.com/ArduPilot/ardupilot/issues/6248 ?

**Comment by sashan13** [comment] 2017-09-06 09:59
Yes.

**Comment by OXINARF** [comment] 2017-09-06 10:07
Duplicate of #6248

**Closed by OXINARF** 2017-09-06 10:07 UTC
