### ISSUE TITLE
Bug: Remove 4 second pause before landing command is executed caused by EKF failsafe logic

### ISSUE THREAD

**Issue by rrr6399** [ArduPilot/ardupilot#2334] opened 2015-05-26 18:56 UTC
I was recently flying a copter with firmware 3.2.1 using a GCS. The copter was flying in AUTO mode and was either in CONDITION YAW with a target of 60 degrees or unlimited loiter with a target altitude of 7m. For some reason that I'm still trying to figure out, it took off across the field. I immediately switched it to LAND mode, but according to the logs, that caused an EKF failsafe and it appears form the code below that the land command was delayed 4 seconds. I wasn't aware that there was a delay and the copter was heading for trees so I killed the motors resulting in a hard crash. 
https://github.com/diydrones/ardupilot/blob/master/ArduCopter/ekf_check.pde#L132
https://github.com/diydrones/ardupilot/blob/master/ArduCopter/control_land.pde#L203
https://github.com/diydrones/ardupilot/blob/master/ArduCopter/control_land.pde#L103

I don't know the history behind this 4 second  delay, but it is an eternity during an emergency situation. In retrospect, I may have switched it to stabilize, but if the 4 second delay could be removed during a pilot-commanded-land, I believe it would allow more robust and non-surprising operations from a GCS during  emergency situations.

**Comment by rrr6399** [comment] 2015-05-26 19:16
Here is the altitude and EKF error history:
![ekf-history](https://cloud.githubusercontent.com/assets/2707426/7821051/ca96ef90-03b1-11e5-8220-c26d7cd33e59.png)

**Comment by rrr6399** [comment] 2015-05-26 19:29
Here is the yaw target and yaw measurment. Not sure why it is ramping down like that. The yaw target was set to a constant 90 degrees.
![yaw-history](https://cloud.githubusercontent.com/assets/2707426/7821281/65411510-03b3-11e5-9fac-b804b8afd112.png)

**Comment by rmackay9** [comment] 2015-05-27 03:13
The crash was likely caused by a heading error (bad compass, bad gyro calibration, etc).  The bad heading would have been detected by DCM or EKF and the EKF Check would have triggered the Land.

The 4sec delay is not a technical question so much as a UX question.  The delay was added after multiple people complained that they had no time to react to a failsafe induced land before the vehicle started descending (into the water, into the trees, etc).  I think it's unlikely we can get rid of the delay without a consensus that it's addition has done more harm than good.

**Comment by rmackay9** [comment] 2015-05-27 03:15
I think the way to get that consensus is to email drones-discuss@googlegroups.com and get a few people to agree.
Sorry to be annoying but I'm going to close this issue for now because there's no way to act on this request without that consensus.

**Comment by rrr6399** [comment] 2015-05-27 12:36
I actually commanded it to Land and it apparently delayed my request due to this logic. Its almost like the EKF failsafe logic was activated by changing the mode to Land.

Its possible that it hit this failsafe right before I commanded it to land, but the odds seem low.

I will take a look at the log to see if the land command got through at the exact time as the EKF failsafe was signaled.

**Comment by rrr6399** [comment] 2015-05-29 14:39
Here are the results from the auto-analysis capability in Mission Planner:
Log File C:/Users/Rob/AppData/Local/Temp/tmp9892.tmp.log
Size (kb) 527.400390625
No of lines 7614
Duration 0:00:39
Vehicletype ArduCopter
Firmware Version V3.2.1
Firmware Hash 36b405fb
Hardware Type 
Free Mem 0
Skipped Lines 0

Test: Autotune = UNKNOWN - No ATUN log data
Test: Balance/Twist = GOOD - 
Test: Brownout = FAIL - Truncated Log? Ends while armed at altitude 13.47m
Test: Compass = GOOD - mag_field interference within limits (24.80%)

Test: Dupe Log Data = GOOD - 
Test: Empty = GOOD - 
Test: Event/Failsafe = GOOD - 
Test: GPS = GOOD - 
Test: IMU Mismatch = NA - 
Test: Parameters = GOOD - 
Test: PM = GOOD - 
Test: Pitch/Roll = GOOD - 
Test: Thrust = GOOD - 
Test: VCC = GOOD -

**Comment by rrr6399** [comment] 2015-05-29 14:56
It looks like the LAND mode change I issued stimulated the EKF FAILSAFE:
![land-bug](https://cloud.githubusercontent.com/assets/2707426/7885338/e46607b0-05e8-11e5-90e2-8d147de42bbf.png)

I think there is a bug in the logic and prevented my LAND command from taking effect until too late.

**Comment by rrr6399** [comment] 2015-05-29 14:59
Randy, would you reopen this. I believe there is an actual bug in the firmware related to issuing the LAND command and it doesn't require a policy decision.

**Comment by magicrub** [comment] 2015-06-05 16:18
@rmackay9 Please re-evaluate and re-close if necessary.
@rrr6399 Per Randy's suggestion, please open up a drones discuss email.

**Comment by rrr6399** [comment] 2015-06-05 16:34
It appears from the logs of two failed fly away flights with two separate copters that when the pilot initiated the LAND command via the GCS that the LAND command triggered the EKF failsafe logic not vice-a-versa. This failsafe logic has a 4 second delay logic that I suspect is causing the delay in the LAND command. Since it appeared that the copters were out of control given that the change to LAND mode was being ignored by the firmware, the both copters were disarmed in flight leading to hard crashes.

**Comment by rrr6399** [comment] 2015-06-05 16:45
Here's altitude and history of the copter that crashed, which also didn't respond to the GCS commanded LAND command. Notice the EKF errors as well when the Land mode was initiated.
![image](https://cloud.githubusercontent.com/assets/2707426/8010714/05871a94-0b78-11e5-97d5-7721bec6838c.png)

Here's the full flight:
![image](https://cloud.githubusercontent.com/assets/2707426/8010737/516ea940-0b78-11e5-85d5-36da69a84e94.png)

**Comment by rmackay9** [comment] 2015-06-06 00:26
Is there a log file somewhere?

**Comment by rrr6399** [comment] 2015-06-07 15:26
@rmackay9, I'll get you log files. Are you looking for anything particular in the results?

**Comment by rmackay9** [comment] 2015-06-09 02:05
Here's the competing request asking to go in the other direction (i.e. increase the delay): https://github.com/diydrones/ardupilot/issues/1905

**Comment by magicrub** [comment] 2015-06-09 03:28
Perhaps a time param will make everyone happy?

**Comment by rmackay9** [comment] 2015-06-09 03:39
To some extent I think the basic problem is that the pilot doesn't know the status of the vehicle and no matter how long the delay is or isn't it will not properly convey the situation.  I think increasing pilot awareness is best done through a ground station or transmitter that can yell out alerts to the pilot especially in these critical cases where control is passed between pilot and autopilot.

**Comment by rrr6399** [comment] 2015-06-09 04:25
I think one thing that is being missed in this case is that I commanded the copter to Land and it ignored it for 4 seconds. That is different from the failsafe scenario. I believe that for some reason, the EKF logic was activated by the GCS's Land request.

**Comment by peterbarker** [comment] 2021-07-30 04:36
We now have `set_mode_land_with_pause(ModeReason::EKF_FAILSAFE)` to cover this.

**Closed by peterbarker** 2021-07-30 04:36 UTC
Labels: Copter
