### ISSUE TITLE
Plane: LOITER_TIME causes quadplane to flip over and crash

### ISSUE THREAD

**Issue by expntly** [ArduPilot/ardupilot#8488] opened 2018-05-24 23:22 UTC
#### Issue details
We had tried the `LOITER_TIME` command before as [described in the doc here](http://ardupilot.org/plane/docs/quadplane-auto-mode.html#hovering-in-a-mission) and this led to a catastrophic crash.  We've tried again with a much simpler mission this time and this led to a crash again.

We have `Q_GUIDED_MODE=1`, `Q_ENABLE=2` and the mission was simply:
 - `VTOL_TAKEOFF` at 12 meters
 - `LOITER_TIME` for 10 seconds
 - `VTOL_LAND` at 0 meters

The vehicle climbed (higher than it should) and then just flipped over and crashed.

#### Version
ArduPlane-385beta1

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
X4 quadplane

#### Hardware type
PH2.1

#### Logs
https://drive.google.com/open?id=1pFmOK65QeDeqO2pJwrclpZZShzoMEn8m

**Comment by magicrub** [comment] 2018-05-24 23:34
hmm.. I doubt it was caused by the LOITER_TIME, it works just like any other LOITER_* command just has different logic to pass before it move to next mission item.

**Comment by expntly** [comment] 2018-05-24 23:52
We've never really managed to make any LOITER_* command work with a quadplane to be honest.

Things were fine until "Executing nav command ID # 19" (which is LOITER_TIME), at which point the vehicle pitched up more than 90 degrees and this was the end.

<img width="1236" alt="screen shot 2018-05-24 at 6 45 46 pm" src="https://user-images.githubusercontent.com/6870452/40518958-b987601a-5f82-11e8-9099-499fb62b9907.png">

It's worth noting that we did a VTOL_TAKEOFF + VTOL_LAND mission just before and landed the vehicle.

**Comment by expntly** [comment] 2018-05-25 00:30
Here's the log for two consecutive `VTOL_TAKEOFF + VTOL_LAND` missions that succeeded just before that `VTOL_TAKEOFF + LOITER_TIME + VTOL_LAND` mission crash: 
 https://drive.google.com/open?id=14a74ice6M7EK5HTBA6i4vRoPm-OcDCIp

<img width="1645" alt="screen shot 2018-05-24 at 7 28 36 pm" src="https://user-images.githubusercontent.com/6870452/40520027-b95af4f2-5f88-11e8-9044-317a3cf27e21.png">


So clearly there seems to be something terribly wrong with LOITER_TIME in this instance.

**Comment by peterbarker** [comment] 2018-05-25 10:58
On Thu, 24 May 2018, expntly wrote:

> So clearly there seems to be something terribly wrong with LOITER_TIME in this instance.

Does this reproduce in SITL?

**Comment by expntly** [comment] 2018-05-25 15:37
Not sure yet.  What would cause the vehicle to pitch up immediately when it executes LOITER_TIME?  Since the whole thing is in AUTO, does it go from one controller to another when it finishes the climb and starts LOITER_TIME?

**Comment by Naterater** [comment] 2019-01-05 06:16
@WickedShell, I think you may be able to tell if this is a support issue or a code issue. Does Loiter work for you?

**Comment by aabs7** [comment] 2021-02-11 06:11
I have the same issue [here](https://github.com/ArduPilot/ardupilot/issues/16491#issue-799985857). But @robustini  said that I am preparing the mission wrong. The issue was closed by saying it's a user setup problem.



> On Thu, 24 May 2018, expntly wrote: So clearly there seems to be something terribly wrong with LOITER_TIME in this instance.
> Does this reproduce in SITL?

@peterbarker  This doesn't reproduce in SITL, instead it works perfectly. What is the problem here?

**Comment by IamPete1** [comment] 2021-07-26 13:46
Sounds like its working in SITL, i'm going to close.

**Closed by IamPete1** 2021-07-26 13:46 UTC
Labels: Plane, VTOL-Plane
