### ISSUE TITLE
Copter: too fast taking off in Guided_NoGPS

### ISSUE THREAD

**Issue by korigod** [ArduPilot/ardupilot#5131] opened 2016-11-03 15:23 UTC
#### Issue details
We have an issue using Guided_NoGPS mode. When we try to take off sending SET_ATTITUDE_TARGET with thrust > 0.5, copter takes off very fast and stop ascending only at 3-4 meters even if thrust is set to 0.5 or lower immediately after lift off.
It happens even when thrust only slightly exceeds 0.5 (e.g. thrust = 0.501).

#### Version
APM:Copter 3.4.1.

#### Platform
[   ] All
[   ] AntennaTracker
[X] Copter
[   ] Plane
[   ] Rover

#### Airframe type
Octocopter.

#### Hardware type
Pixhawk.

**Comment by OXINARF** [comment] 2016-11-03 15:38
This should typically be posted first in the forum since this issues list is for confirmed bugs and feature requests.
But since you opened it please provide a log.

**Comment by OXINARF** [comment] 2016-12-17 20:52
No answer for one month and a half, closing.

**Closed by OXINARF** 2016-12-17 20:52 UTC
Labels: Copter, NeedAnswer
