### ISSUE TITLE
Uart delay start when power on

### ISSUE THREAD

**Issue by Abner0907** [ArduPilot/ardupilot#17224] opened 2021-04-19 04:31 UTC
Hi, I am not sure this is only my issues. I am very appreciate that some one can look the details. 

I have the text that:
I add a power button in my private hardware. When I push the button, the system is power on and start working(_Push HIGH  a gpio pin_), everything work as expected. But When I look at the `AP_SerialManager` thread.  The system can get in the code below after 5 seconds. I can not catch the reason. 
![Screenshot from 2021-04-19 12-22-23](https://user-images.githubusercontent.com/64906552/115181177-eee9a800-a109-11eb-9c7d-3dc4db69ed92.png)
**BTW**
1: My hardware is modified but similar as the pixhawk V4.
2: _The code call/initialize in the [init_ardupilot](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/system.cpp#L16) function without delay._
3: I add a new serial protocol `SerialProtocol_CodevEsc = 40`

**Comment by magicrub** [comment] 2021-04-19 06:11
I don't think I understand the question

**Comment by Abner0907** [comment] 2021-04-19 06:46
@magicrub  The uart start to work  later 5 seconds  than the bootloader is started or system power plug in?

**Comment by andyp1per** [comment] 2021-04-19 07:22
There is always a 5 second delay at boot by design

**Comment by Abner0907** [comment] 2021-04-19 10:20
>There is always a 5 second delay at boot by design

@andyp1per  Hi, is this hide in the bootloader? If so, I will review the bootloader code

**Comment by WickedShell** [comment] 2021-05-18 22:51
> > There is always a 5 second delay at boot by design
> 
> @andyp1per Hi, is this hide in the bootloader? If so, I will review the bootloader code

Yes, this is by design and inside the bootloader. I'm closing as this appears to be a support issue best asked on discord or the forums.

**Closed by WickedShell** 2021-05-18 22:51 UTC
