### ISSUE TITLE
ArduCopter V3.4.2-rc2,DO_DIGICAM_CONTROL do not works

### ISSUE THREAD

**Issue by gechangli** [ArduPilot/ardupilot#5206] opened 2016-11-14 04:00 UTC
#### Issue details
I can trigger the servo by pressing the "trigger camera now" button in mission planner "actions", but the command DO_DIGICAM_CONTROL does not trigger the servo/camera.I set the value of param5=1,but read again the value of param5 changed  to 1.28e-5

#### Version
APM:Copter V3.4.2-rc2

#### Platform
 
[  ] Copter
 

#### Airframe type
hex

#### Hardware type
pixhawk

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by OXINARF** [comment] 2016-11-14 04:45
1. This is a support question and those should be posted at the forum (http://discuss.ardupilot.org)
2. When you do the _Trigger Camera Now_ in Mission Planner, it uses the command DO_DIGICAM_CONTROL, so that shows the issue isn't in ArduPilot
3. I'm not sure  what you mean with reading again the value of param5

For all the above reasons, I'm going to close this. Feel free to post in the forum if you need help.

**Closed by OXINARF** 2016-11-14 04:45 UTC
