### ISSUE TITLE
Plane: Loiter radius when writing WP's, jumps down to 244m or 24m

### ISSUE THREAD

**Issue by MRazgunas** [ArduPilot/ardupilot#602] opened 2013-10-12 16:05 UTC
When writing WP's, loiter radius jumps down to 244, sometimes to 24. As we are using APM in 224km/h(140 MPH) plane this is big deal for us, because plane cant't fit to 244m radius.

**Comment by gmorph** [comment] 2015-09-07 12:21
Closing as this is a support issue.  If you can post logs to the support forums we would be happy to help.
Thanks, Grant.

**Comment by vierfuffzig** [comment] 2019-04-10 21:37
i reopened this because there's a reproducible issue with WP_LOITER_RADIUS going back to 0 when trying to set a value higher than 255, possibly for being stored as int8_t somewhere. 
see https://discuss.ardupilot.org/t/loiter-command-plane-mission-planner/40921/3 for reference.

spotting the exact cause is beyond my scope, i did reproduce it on different vehicle firmwares as well as with different GCSes (MP / QGC).

thanks for looking into this, 
basti.

**Comment by tridge** [comment] 2019-04-11 06:57
yes, radius in LOITER_TURNS is limited to 8 bits in the current implementation, and it is quite hard to fix.
What you can do is set it to zero and it will use the WP_LOITER_RAD parameter, which has a max of 32767

**Comment by vierfuffzig** [comment] 2019-04-11 07:13
thanks @tridge so if i get this right, at the moment there‘s no option to command individual radii above 255 other than what WP_LOITER_RAD is set to.

**Comment by tridge** [comment] 2019-04-11 07:37
yes, sorry!

**Comment by vierfuffzig** [comment] 2019-04-11 10:20
np, thanks for looking into this. being more of a functional limitation than an issue i‘m closing this.

**Closed by vierfuffzig** 2019-04-11 10:20 UTC
Labels: Plane
