### ISSUE TITLE
Fast takeoff in poshold mode to midair then continue small shift can't hold its position

### ISSUE THREAD

**Issue by askariz** [ArduPilot/ardupilot#9442] opened 2018-09-18 01:29 UTC
### Bug report

**Issue details**

Fast takeoff (First let PILOT_SPEED_UP to 10m/s then full throttle takeoff in poshold mode) in poshold mode to midair then continue small shift can't hold its position !
![image](https://user-images.githubusercontent.com/39890252/45658720-44f5a980-bb23-11e8-96a5-9a64b4453438.png)

And I find it due to code in **mode_poshold.cpp** there are 3 call for **loiter_nav->init_target();**
![image](https://user-images.githubusercontent.com/39890252/45658955-8dfa2d80-bb24-11e8-89a5-420e77552f4e.png)

**Version**
copter-3.6/master

**Platform**
[  ] All
[  ] AntennaTracker
[ ✔ ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
hex copter

**Hardware type**
SITL & PX4-V2

**Logs**
https://drive.google.com/file/d/1dChBmx2aOMKALWHLzCjgYflMhGAB6Wgg/view

**Comment by lthall** [comment] 2018-09-18 07:14
Sorry but it is not clear what you are saying the problem is. I can't even see what you have plotted in your graph.

Could you please attempt to describe this problem in more detail.

**Comment by lthall** [comment] 2018-09-18 08:08
Ok, I think I see what you are saying and I think I have fixed the issue.

Could you test this?

https://github.com/lthall/Leonard_ardupilot/tree/20180918-PosHoldFix

Thank you very much for bringing this to our attention!!

**Comment by askariz** [comment] 2018-09-18 08:34
HI , I have tested your commit with SITL then the problem solved . 
Thank you .

**Comment by lthall** [comment] 2018-09-18 08:58
Thanks!!!

**Comment by rmackay9** [comment] 2018-09-18 23:34
fix merged into master and will go out with -rc11.

**Closed by rmackay9** 2018-09-18 23:34 UTC
