### ISSUE TITLE
fix handling of lidar I2C nack 

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#1793] opened 2015-01-19 23:00 UTC
the ll40ls lidar sometimes fails, possibly due to not correctly handling I2C nack responses. We need to investigate and fix

**Comment by rmackay9** [comment] 2015-01-20 00:20
I think this is a duplicate of this existing issue.  https://github.com/diydrones/ardupilot/issues/1770
I've closed the other one.

**Comment by magicrub** [comment] 2015-05-06 19:43
is this considered done?

**Comment by Naterater** [comment] 2019-01-07 06:45
Might this be fixed with recent PR's such as https://github.com/ArduPilot/ardupilot/pull/9794?

**Comment by IamPete1** [comment] 2022-08-06 16:32
I'm going to close. Please re-open if this is still a problem.

**Closed by IamPete1** 2022-08-06 16:32 UTC
Labels: Copter, Plane
