### ISSUE TITLE
Pixhawk: More than 8 channels PPM in and passthru on AUX channels

### ISSUE THREAD

**Issue by sgofferj** [ArduPilot/ardupilot#1040] opened 2014-05-01 11:17 UTC
I know that's already partially available in Plane but AFAIK only for SBUS, not for PPM.

Looking at new RC systems like the Taranis but also e.g. OpenLRSng, those systems can deliver 16 channels via PPM (some also via SBUS).
It would be very useful to be able to make use of all those channels
1.) for extra autopilot functions and
2.) with passthru on the AUX channels

With FrSky it is possible to use 2 receivers, the first piping ch1-8 into the PH via PPM and the second to offer ch 9-16 on it's outputs but I would still find using the AUX channels on the PH preferable because it also opens the possibility for the firmware to control/override AUX devices later.

**Comment by xoxota99** [comment] 2015-04-10 02:23
still not working in latest ArduCopter. Running SBUS on FrSky X4R-SB w/ Taranis. Eight channels coming through just fine, and receiver is detected as an 18-channel receiver, but channels 9-16 are not coming through.

**Comment by scotty0717** [comment] 2015-04-10 12:13
Well like I said, I don't think we have that option yet. Were stuck with 8
channels until they make a change.

**Comment by lvale** [comment] 2015-04-10 20:17
Hi
I believe the issue is on Mission Planner, not Arducopter 3.2.1

I'm using with no issues, up to channels 12 (didn't try higher) on the Aux ports (Receiver Channels 9, 10, 11, 12) of the PixHawk, from a X8R receiver via SBUS.

**Comment by sgofferj** [comment] 2015-04-11 02:58
The issue is about PPM, not S.BUS.

**Comment by xoxota99** [comment] 2015-04-13 22:57
I see this issue on SBUS as well. @Luis, interesting that you're only
seeing the problem in Mission Planner. I'll have to test that out. Thanks!

**Comment by scotty0717** [comment] 2015-10-04 20:54
Hi,

I'd like to add you to my professional network on LinkedIn.

- Justin

Confirm that you know Justin: https://www.linkedin.com/e/v2?e=k81q8o-ifczkl65-1p&amp;t=ssuw&amp;tracking=eml-guest-invite-cta&amp;ek=invite_guest&amp;sharedKey=kMCrFsOO&amp;invitationId=6056541527197446144








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=k81q8o-ifczkl65-1p&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGXeVrM4bgQUQAAAVA0ofln89ESgszqSK4KWy0GOu7x3mixvx5-bWlm2fJJw-c9vRjmvqGU0KHFVVWL5aELCqE9yS5gKWpFNYSLEwyZHKrDU71fJb8McIFkGzbFLWLuGBxmXJZIcBG8zUhqzsHzBtEe2Lb3du8UroSY8boSi0tdPfDx9wh_U01W9Z_JPfK3jl1O&eid=k81q8o-ifczkl65-1p


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=k81q8o-ifczkl65-1p&a=customerServiceUrl&ek=invite_guest

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by marcmerlin** [comment] 2015-12-04 22:18
So, I've tried to get more than 12 channels with my LRS system using PPMout, and failed.
Anything after 12, is not visible 
chan13_raw and chan14_raw are pegged at 0.

**Comment by marcmerlin** [comment] 2015-12-04 22:20
I should add that PPM channels up to 12, work, and I can use them for functions like geofence switch, or passthrough.

**Comment by marcmerlin** [comment] 2015-12-14 16:37
I've opened a new bug to specifically track support for 16 channels instead of 12 with CPPM/PPMSUM: https://github.com/diydrones/ardupilot/issues/3337
I suppose we can close this bug since "more than 8 channels" as per the title, has been fixed.
Now we need "more than 12 channels" :)

**Comment by marcmerlin** [comment] 2015-12-14 16:49
Actually can anyone on this bug confirm that no one has seen more than 12 channels via PPMSUM?
I'm reading the code and not fnding an obvious reason why only 12 channels are going through (details in #3337)

**Comment by Ravid824** [comment] 2016-07-14 08:07
I run PPM 12 Chanel TX/RX and I don't anything in Mission Planner above Ch8
I run PM:Copter V3.3.3 on Pixhawk and the latest mission Planner. 
I don't know what to expect, should I see all channels in Radio calibration screen? Should I see the added channels 9-12 in the Extended Tuning window?
Below is the receiver PPM out  signal  which repose well to any TX channel changes. Frame length (Frame start to next frame start) is about 32 Msec , while after channel #12 it shows about 16 Msec until the next frame starts. 
Can some one direct me on what need to be done please.
![image](https://cloud.githubusercontent.com/assets/14961646/16832142/c912aacc-495d-11e6-842d-27f8c8d4ef52.png)

**Comment by OXINARF** [comment] 2016-11-24 00:12
Closing as this is fixed, next issue is #3337

**Closed by OXINARF** 2016-11-24 00:12 UTC
Labels: Enhancement, PX4

**Comment by marcmerlin** [comment] 2016-11-24 00:16
@OXINARF  thanks. Hopefully the more than 12 channels on CCPM gets fixed too :)
