### ISSUE TITLE
Copter: A bug in rate_to_accel_z()

### ISSUE THREAD

**Issue by luweikxy** [ArduPilot/ardupilot#6579] opened 2017-07-12 06:03 UTC
After this line.
https://github.com/ArduPilot/ardupilot/blob/ba011eef78ba7ef401a64b12d5a6d130dbe9dd02/libraries/AC_AttitudeControl/AC_PosControl.cpp#L423

may add "_accel_feedforward.z = 0.0f;"

@rmackay9

**Comment by lthall** [comment] 2017-07-12 13:01
Thanks for looking at this luweikxy!

This is not a bug the idea is the feedforward is being held constant in this case, therefore we don't want to set it to zero.

**Comment by magicrub** [comment] 2017-07-12 14:07
@lthall and @luweikxy sounds like we should close this?

**Comment by luweikxy** [comment] 2017-07-12 23:21
@lthall  OK, thank you!

@magicrub  Yes, it can be closed.

**Closed** 2017-07-13 00:09 UTC
Labels: Copter
