### ISSUE TITLE
RCMAP for all channels

### ISSUE THREAD

**Issue by svefro** [ArduPilot/ardupilot#1096] opened 2014-05-22 00:37 UTC
I'm using a spectrum transmitter with a FRSky module.

Until now i have been connecting the receiver channel by channel but today i wanted to try my new D4R-II Receiver (in CCPM) and since spectrum have a fixed channel order i can't get my 3pos switch to channel 5 for flight modes (I mix and get all 6 with another switch ofc).
I had to use RCMAP on AIL/ELEV and THR to get those right.

I propose that we should be able to map all channels with RCMAP and rename CH7/8 to AUX1 and AUX2 to avoid confusion of the new channel order.

This way all channels could be mapped from 1-8

RCMAP_Pitch
RCMAP_Roll
RCMAP_Yaw
RCMAP_THR
RMMAP_FLIGHTMODE
RCMAP_TUNE (ch6)
RCMAP_AUX1 (ch7)
RCMAP_AUX2 (ch8)

I see that other users have the same problem when using a spectrum satelite reciever with the Pixhawk.

http://diydrones.com/forum/topics/setting-channel-assignments-at-pixhawk-for-spektrum-dx7

**Comment by DavidIngraham** [comment] 2018-05-04 21:00
Tagging this so with #8170 so we can remember to close it when that goes in

**Comment by DavidIngraham** [comment] 2018-05-04 21:17
Also closing #1031 as it is very similar to this

**Comment by WickedShell** [comment] 2018-06-25 09:30
Closing this one now, since it's a duplicate of #1031, and has a PR in to resolve it.

**Closed by WickedShell** 2018-06-25 09:30 UTC
Labels: Copter, Enhancement
