### ISSUE TITLE
ArduCopter autotests fail if --frame octa-quad (ATC_RAT_RLL_D gets zeroed)

### ISSUE THREAD

**Issue by amilcarlucas** [ArduPilot/ardupilot#10295] opened 2019-01-21 14:09 UTC
### Bug report

ArduCopter autotests for octa-quad-frame fail

The cause seams to be that ATC_RAT_RLL_D is set to 0, making the pre-arm checks fail:
`APM: PreArm: Check PIDs - ATC_RAT_RLL_D`

that has to be a bug because the octa-quad parameter file sets that one to 0.022 and the SITL gets that message:
`changed ATC_RAT_RLL_D from 0.003600 to 0.002220`

to reproduce this issue:

`cd arducopter`
`./Tools/autotest/autotest.py build.ArduCopter defaults.ArduCopter fly.ArduCopter --frame octa-quad`

**Version**
master

**Platform**
[  ] All
[  ] AntennaTracker
[ *] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
octa-quad

**Hardware type**
SITL

**Logs**
https://gist.github.com/karthikdesai/89a883f075e87c8e9557dc0576cd48f9#file-log-txt

**Comment by IamPete1** [comment] 2019-01-21 14:53
Probably due to the this https://github.com/ArduPilot/ardupilot/pull/10214

**Comment by richardor-cell** [comment] 2020-02-09 06:46
Hi, please where could be found X8 sdf example file as for the iris quad demo to reproduce this ?

**Comment by IamPete1** [comment] 2021-08-29 17:49
Fixed by https://github.com/ArduPilot/ardupilot/pull/10214 

We now allow 0 d term, but not negative.

**Closed by IamPete1** 2021-08-29 17:49 UTC
Labels: BUG, Copter
