### ISSUE TITLE
Quadplane: pitch rudder to operate in VTOL modes

### ISSUE THREAD

**Issue by najia2010** [ArduPilot/ardupilot#10302] opened 2019-01-22 07:49 UTC
@tridge [https://github.com/ArduPilot/ardupilot/issues/4459](url)
The latest firmware 3.9.5 and V3.10.0-dev VTOL mode, the fixed-wing pitch rudder can not work when starting to take off, the windy weather is very unfavorable for the aircraft to stabilize. Request to add a switch to control the pitch rudder. Losing the fixed-wing rudder surface self-stabilization in bad weather is really bad for VTOL mode. Thank you

**Comment by magicrub** [comment] 2019-01-22 19:42
closing, duplicate of https://github.com/ArduPilot/ardupilot/issues/4459

**Closed by magicrub** 2019-01-22 19:42 UTC

**Comment by najia2010** [comment] 2019-01-23 01:58
@magicrub:I very much hope that in VTOL mode, the fixed-wing pitch rudder can help the aircraft control the flight attitude during the take-off phase.。Do you have any good suggestions?

**Comment by magicrub** [comment] 2019-01-23 16:22
seems like a useful fix, but posting a duplicate thread makes us spend time explaining that it's a duplicate thread instead of actually working on stuff. I'm freezing msgs on this thread, please use the other one
