### ISSUE TITLE
Battery: support reading voltage of each cell

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#6285] opened 2017-05-19 20:06 UTC
support reading voltage of each cell

**Comment by magicrub** [comment] 2017-05-19 20:06
Ping @marcmerlin

**Comment by WickedShell** [comment] 2017-05-19 20:13
@magicrub What is the issue for? This is capable with a SMBus battery, and there aren't enough ADC ports to do direct monitoring of any other battery cells?

**Comment by lvale** [comment] 2017-05-19 20:31
@WickedShell If we can have this with a SMBus battery then it is an incentive to get wider adoption of these.
This might pose other issues, like defining the current voltage settings on a per cell value and adding a new value with the number of cells

**Comment by WickedShell** [comment] 2017-05-19 20:33
@lvale yeah, it's done though :)

I don't know what you mean by current voltage settings per cell? Your SMBus device does the work for you,  you don't have to worry about it after that? I'm still confused what the issue is asking for :)

**Comment by lvale** [comment] 2017-05-20 07:28
This:

<img width="597" alt="screen shot 2017-05-20 at 08 21 27" src="https://cloud.githubusercontent.com/assets/3130363/26274022/467b49a2-3d36-11e7-90fe-4213d348c750.png">

**Comment by marcmerlin** [comment] 2017-05-20 07:50
Also, it would be totally fantastic if one of the serial port on the pixhawk to be configured to be compatible with the frsky Sport 1 wire protocol.
We'd then get lots of cool and cheap sensors like
http://www.getfpv.com/frsky-flvss-lipo-voltage-sensor-with-smartport.html
and
http://www.getfpv.com/smart-port-rpm-sensor-with-2-temperature-sensors.html
The RPM sensor thing on AUX4/5 has never worked for me despite trying quite a bit, and it only works with certain ESCs. The frsky one works with any ESC while giving you 2 temps you can measure too.
But back to the lipo per cell sensor, you get that easily with their sensor on all your existing batteries.
Having to replace all our batteries just so that ardupilot can talk to them, seems like a no go for many when a simple $17 sensor takes care of that (and it even has a screen with readouts on it)
![image](https://cloud.githubusercontent.com/assets/1369412/26274103/5b1ab798-3cf6-11e7-9be9-a8cb699eff22.png)

**Comment by marcmerlin** [comment] 2017-05-22 05:47
I opened a new issue to deal with reading Taranis sensors: https://github.com/ArduPilot/ardupilot/issues/1587
If it is solved, then in turn it would solve this issue easily.

**Comment by OXINARF** [comment] 2017-05-22 13:55
I still don't get what this issue is for. We already support reading the cell voltages where it is available. Supporting a new battery monitor is fine, but that's not what this issue says - and I guess #6296 already covers that request.

**Comment by WickedShell** [comment] 2017-05-24 22:01
Closing this in favor of #6296 as it more clearly describes the top level issue, and the core things that need to be done to read that sensor.

**Closed by WickedShell** 2017-05-24 22:01 UTC
Labels: Library
