### ISSUE TITLE
Copter: allow tuning of loiter speed using CH6 tuning knob

### ISSUE THREAD

**Issue by thecodingfrog** [ArduPilot/ardupilot#3225] opened 2015-11-24 21:16 UTC
I've been able to change WP speed using CH6, but changing loiter speed doesn't work

**Comment by rmackay9** [comment] 2015-11-28 01:20
the wp-speed is separate from the loiter speed.  The wp-speed only affects the speed using missions.  
We don't currently support ch6 tuning of the loiter speed although it could be updated from the ground station's parameter list... but it won't take effect until the pilot switches out and then back into loiter.
I'm going to close this if that's ok but i'll still see comments posted here.

**Comment by thecodingfrog** [comment] 2015-11-28 07:38
So it is in the list but not available yet ?

Jean-Louis PERSAT

Le 28 nov. 2015 2:21 AM, Randy Mackay <notifications@github.com> a écrit :

the wp-speed is separate from the loiter speed. The wp-speed only affects the speed using missions.

We don't currently support ch6 tuning of the loiter speed although it could be updated from the ground station's parameter list... but it won't take effect until the pilot switches out and then back into loiter.
I'm going to close this if that's ok but i'll still see comments posted here.

**Comment by rmackay9** [comment] 2015-11-28 09:59
@thecodingfrog, i'm afraid the loit-speed thing is not even in the list.

**Comment by thecodingfrog** [comment] 2015-11-28 11:56
Sure it is!

Jean-Louis PERSAT

Le 28 nov. 2015 11:01 AM, Randy Mackay <notifications@github.com> a écrit :

@thecodingfrog, i'm afraid the loit-speed thing is not even in the list.

**Comment by thecodingfrog** [comment] 2016-05-28 09:59
Any info since I've open this ?
Loiter speed is still available on CH6_OPT list but still doesn't change the loiter speed.
![img_20160528_114923](https://cloud.githubusercontent.com/assets/12624593/15626686/9bb2891e-24cb-11e6-9746-8a0ed6aede78.jpg)

**Comment by OXINARF** [comment] 2016-05-28 12:53
That Loiter Speed label is indeed wrong. And no, this still hasn't been implemented. Anyway, we are changing tuning to a new library that Plane is already using, so this will probably be fixed then.

**Comment by thecodingfrog** [comment] 2016-05-28 14:49
That sound good

Jean-Louis PERSAT

Le 28 mai 2016 2:54 PM, Francisco Ferreira <notifications@github.com> a écrit :

That Loiter Speed label is indeed wrong. And no, this still hasn't been implemented. Anyway, we are changing tuning to a new library that Plane is already using, so this will probably be fixed then.

**Comment by thecodingfrog** [comment] 2016-10-24 09:17
Hi,
Any news about this ?

**Comment by OXINARF** [comment] 2016-10-24 13:16
@thecodingfrog No, unfortunately no. We are in the final stages of releasing Copter-3.4 and this didn't make it. Hopefully we can get it in the next release.

**Comment by thecodingfrog** [comment] 2016-10-24 13:24
would be really interesting to have it :)
and beside this when we don't need any tuning from CH6 options would be also cool to be able to use CH6 for something else (parachute, autotune) like we do with CH7 et CH8

**Comment by R-Lefebvre** [comment] 2016-10-26 00:15
And at the same time, would be nice to be able to use Ch7 and 8 to do tuning different values,so you could tune 3 PID variables at the same time, for example.  I had done this almost 2 years ago but it didn't make it.

**Comment by Naterater** [comment] 2019-01-08 23:48
This issue is a bit old. Is there a possibility that this has been solved recently?

**Comment by IamPete1** [comment] 2021-08-30 22:36
duplicate of https://github.com/ArduPilot/ardupilot/issues/9782

**Closed by IamPete1** 2021-08-30 22:36 UTC
Labels: Copter
