### ISSUE TITLE
Help!......when i cloned the code by github, there is error when make by tooltrain.

### ISSUE THREAD

**Issue by sunboygq** [ArduPilot/ardupilot#5254] opened 2016-11-22 02:12 UTC
#### Issue details
_Please describe the problem, or desired feature_
I have cloned the code by using "Clone or down-> open in desktop"  of github.
After the code cloned over, I did "make px4-v2" in tooltrain, it said:
Traceback (most recent call last):
file "c:/px4/ardupilot/modules/mavlink/pymavlink/tools/mavgen.py", line 16, in <module>
from pymavlink.generator import mavgen
file "c:\px4\ardupilot\modules\mavlink\pymavlink\generator\mavgen.py", line 12 in <module>
from futrue import standard-library
ImporteError : No modulenamed futrue mavgen:failed
make : *** [/c/px4/ardupilot/Build.arducopter/libraries/GCS_MAVLink/include/mavlink/v2.0/ardupilotmega/mavlink.h] Error 1

why there is such error. How to resovle it ?
Can any one help me.
Thanks So much!............

#### Version
_What version was the issue encountered with_
the latest version
#### Platform
[  ] All
[  ] AntennaTracker
[*] Copter
[  ] Plane
[  ] Rover

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_
pixhawk
#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by rmackay9** [comment] 2016-11-22 02:40
Depends which OS you're running on but if it's windows there's an updated Pixhawk Toolchain (linked from the wiki).  If it's Ubuntu then the prerequisite scripts (in the Tools/scripts directory) should install the future python module (which is the cause of the error you're seeing).

I think I'll close this issue because it's been asked (and answered) before.

**Closed by rmackay9** 2016-11-22 02:40 UTC
