### ISSUE TITLE
Plane: RTL_Radius supercedes WP_LOIT_RAD

### ISSUE THREAD

**Issue by falconunmanned** [ArduPilot/ardupilot#4435] opened 2016-07-06 17:45 UTC
#### Issue details

We were flying an unlimited loiter waypoint with an WP_LOITER_RAD of 400m.  We switched the RTL_RADIUS to 150 and the aircraft changed its radius to 150 while in the Auto mode for the loiter unlimited waypoint.  When the full parameter list was viewed the WP_LOITER_RAD was still 400m but doing a 150m radius circle.
#### Version

 3.5.3
#### Platform

[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover

**Comment by magicrub** [comment] 2016-07-06 18:22
confirmed, but I think it was by design due to a request at some point in the past. Does anyone remember? Loiter-unlimited was treated differently for some reason.

here's the logic: https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/commands_logic.cpp#L606
for NAV_LOITER_UNLIMITED the radius is never zero, its either the direction size or it's RTL_RADIUS. It never looks at WP_LOITER_RAD like _TIME and _TURNS does.

**Comment by WickedShell** [comment] 2018-03-10 06:53
Just came across this, I'd say that behaviour is *very* surprising and unintuitive. I'd support removing the special case code that uses RTL's radius here.

**Comment by magicrub** [comment] 2018-03-10 07:58
I think the old old old behavior must have been an RTL event stayed in AUTO and executed loiter unlimited over home. Would have been equivalent behavior. I remember seeing this back when I was making all the loiters share common code and had to treat this one a little different to retain the old behavior.

I vote to remove the special behavior.

**Comment by Naterater** [comment] 2019-01-04 23:05
Confirmed in SITL, but only for LOITER_UNLIMITED.

**Comment by IamPete1** [comment] 2021-07-26 00:47
fixed by https://github.com/ArduPilot/ardupilot/pull/14642

**Closed by IamPete1** 2021-07-26 00:47 UTC
Labels: Plane
