### ISSUE TITLE
Protecting parameters from eeprom from copying after reinstalling the firmware

### ISSUE THREAD

**Issue by NotShittyProgrammer** [ArduPilot/ardupilot#26336] opened 2024-02-27 16:15 UTC
Good afternoon, I am facing a problem - I wrote a custom firmware that does not display values ​​from the eeprom in the mission planner. But when I install the official firmware, the params list appears. I can block it in theory, here's a link on how to do it:

https://ardupilot.org/dev/docs/secure-firmware.html

However, if I install the official firmware through the stm32cubeprogrammer, I will still see the values ​​from the eeprom. Is there any way I can block this or reset the values ​​to default every time someone tries to install a new firmware version?

**Comment by rmackay9** [comment] 2024-02-28 00:25
Hi @NotShittyProgrammer,

I think if your special firmware was modified so that it used a different [FORMAT_VERSION](https://ardupilot.org/copter/docs/parameters.html#format-version) then when the standard firmware is uploaded the [parameters will be reset](https://ardupilot.org/copter/docs/common-parameter-reset.html)

**Comment by rmackay9** [comment] 2024-02-28 00:39
@NotShittyProgrammer,

So I guess you changed [this line in Copter](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/Parameters.h#L28)? .. or this [line in Plane](https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/Parameters.h#L36)?

**Comment by NotShittyProgrammer** [comment] 2024-02-28 00:41
Yep, this line for plane and build a plane firmware

**Comment by rmackay9** [comment] 2024-02-28 01:53
Thanks @NotShittyProgrammer,

I've reproduced the problem in SITL by doing the following:

1. cd ardupilot/ArduCopter
2. rm eeprom.bin (to clear all parameters)
3. start SITL (sim_vehicle.py --map --console)
4. param set MNT1_TYPE 8
5. reboot the autopilot and confirm the parameter MNT1_TYPE is still 8
6. update k_format_version to 121 (currently 120 for Copter)
7. start SITL and confirm that MNT1_TYPE has **not** been reset to 0 as it should have been

If the above procedure is followed for the Copter-4.5 branch the parameter is reset correctly.  If it is done for "master" (aka "latest") the parameter is not reset.  It remains at 8.

**Comment by NotShittyProgrammer** [comment] 2024-02-28 02:02
I did not understand you well. My goal is to erase eeprom parameters when I install new firmware after mine, so no one could see my previous eeprom params list. So I changed format_version to 14 for plane so it would remove old eeprom values. But when I install my new firmware eeprom params did not erased and format_version is still 13.

**Comment by rmackay9** [comment] 2024-02-28 02:05
@NotShittyProgrammer,

Are you using a very recent version of master (aka "latest")?  I think the issue may be due to a recent change..

**Comment by NotShittyProgrammer** [comment] 2024-02-28 02:06
Yes, I am using the latest version. Should I switch to another branch or previos commits?

**Comment by rmackay9** [comment] 2024-02-28 02:31
@NotShittyProgrammer,

I'm not sure, I was able to reproduce the issue once but now I'm unable to.  I've added the issue to [the Copter-4.5 issues list](https://github.com/ArduPilot/ardupilot/issues/26103) although I suspect it only affects master.  I've also alerted @peterbarker who I think is most familiar with this area.

You might want to try following the procedure I've mentioned above for reproducing the issue in SITL.  Basically we need to be able to reproduce the issue in order to narrow down how to fix it.

**Comment by NotShittyProgrammer** [comment] 2024-02-28 02:35
Thanks, I will be waiting for further details🫡

**Comment by rmackay9** [comment] 2024-02-28 04:59
Hi @NotShittyProgrammer,

I've tested further and I think changing k_format_version does actually work.  The issues that I was facing were, I think, caused by unrelated mission planner problems to do with support for the dual CPU CubeRed.

Which autopilot are you using?  I'm happy to create two binaries with only the format_version changed and I think you'll find that loading one of them clears out the autopilot's parameters.

**Comment by NotShittyProgrammer** [comment] 2024-02-28 09:51
I am using current ArduPilot repository and I build firmware for CUAV-X7. But I really need to build it on different controllers. I will try to find older version where this trick with k_format_version work

**Comment by rmackay9** [comment] 2024-02-28 11:30
@NotShittyProgrammer,

OK, although I find that even with master it works.

**Comment by NotShittyProgrammer** [comment] 2024-02-28 12:15
![photo_2024-02-28 14 15 08](https://github.com/ArduPilot/ardupilot/assets/73193992/32a245f8-03ca-4345-9174-d178eb01314d)
![photo_2024-02-28 14 15 11](https://github.com/ArduPilot/ardupilot/assets/73193992/58507dcf-b449-4978-9bd1-1a1481b8f34b)
Still get the same FORMAT_VERSION

**Comment by rmackay9** [comment] 2024-02-29 04:01
@NotShittyProgrammer,

I've created two binaries here built on master.  One has the format-version of 13, the other 14.  Could you try these two?
https://www.dropbox.com/scl/fi/qb5u4z5s66sl3l40ufs3z/arduplane-460dev-cuavx7.zip?rlkey=881sgccw9zijq573vfwug7t22&dl=0

**Comment by rmackay9** [comment] 2024-03-05 01:38
Hi @NotShittyProgrammer,

I'm going to go ahead and close this issue now.  Please tell me if the above binaries don't work for you.

**Closed by rmackay9** 2024-03-05 01:38 UTC
Labels: BUG
