### ISSUE TITLE
Implement MAV_CMD_PREFLIGHT_CALIBRATION for rc calibration

### ISSUE THREAD

**Issue by DonLakeFlyer** [ArduPilot/ardupilot#3287] opened 2015-12-05 22:29 UTC
This could be used to remove the possibility of arming while doing an RC Calibration. QGroundControl already support this mechanism.

**Comment by peterbarker** [comment] 2017-12-19 09:16
Sub has this.  Swipe it for the other vehicle types.

**Comment by bCamba** [comment] 2018-02-15 01:52
@peterbarker I can do that, but how can I test this? (I am new to ArduPilot community)

**Comment by IamPete1** [comment] 2021-08-30 22:34
duplicate of https://github.com/ArduPilot/ardupilot/issues/8735

**Closed by IamPete1** 2021-08-30 22:34 UTC
Labels: good first issue
