### ISSUE TITLE
Win10/UbuntuBash DevEnvironment Setup Instructions Borked

### ISSUE THREAD

**Issue by NachtRaveVL** [ArduPilot/ardupilot#6945] opened 2017-09-13 03:38 UTC
#### Issue details
While following through the Win10/UbuntuBash setup instructions (located http://ardupilot.org/dev/docs/building-ardupilot-onwindows10.html):

```
sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded
sudo apt-get update
sudo apt-get install gcc-arm-none-eabi=4.9.3.2015q3-1trusty1
```

On the `sudo apt-get update` line it gives the following error:
```
W: The repository 'http://ppa.launchpad.net/terry.guo/gcc-arm-embedded/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/terry.guo/gcc-arm-embedded/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Upon attempting to continue with `sudo apt-get install gcc-arm-none-eabi=4.9.3.2015q3-1trusty1` it gives the following error:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '4.9.3.2015q3-1trusty1' for 'gcc-arm-none-eabi' was not found
```

It would appear that skipping adding this repo to the apt-get repo and just installing gcc-arm-none-eabi without a branch specified seems to still build using px4-v3 copter through waf.

#### Version
Latest master branch. Commit b9877e0d3850223ae6c2df3a68c3d888ca5be628.

#### Platform
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
n/a

#### Hardware type
PX4v3

#### Logs
Attached above.

**Comment by OXINARF** [comment] 2017-09-13 16:23
@NachtRaveVL Thanks. This should actually be in the wiki repository and not here, so I'm closing it. In any case, @auturgy has gone ahead and did a pull request so the issue isn't needed anymore.

**Closed by OXINARF** 2017-09-13 16:23 UTC
