### ISSUE TITLE
make px4-v3-upload doesn't upload

### ISSUE THREAD

**Issue by peterbarker** [ArduPilot/ardupilot#5593] opened 2017-01-21 03:09 UTC
#### Issue details
`make px4-v3-upload` should upload to the board on successful compilation.  It doesn't seem to attempt to upload.

#### Version
master

#### Platform
[ X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

**Comment by OXINARF** [comment] 2017-07-31 13:58
#5917 was a duplicate of this and was fixed with #5919, closing.

**Closed by OXINARF** 2017-07-31 13:58 UTC
Labels: AllVehicles, BuildSystem, PX4
