### ISSUE TITLE
Sub: Rate limit motors test messages

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9804] opened 2018-11-15 14:33 UTC
Moved from: bluerobotics/ardusub#162
Original author: @jaxxzer

### Feature request
Somehow, it is possible to get this output in an instant:

```
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
Got MAVLink msg: COMMAND_ACK {command : 209, result : 4}
APM: Arm motors before testing motors.
APM: motor test initialization failed!
```

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by jaylthegreat** [comment] 2019-07-15 19:46
To make this more clear, you can get this (or at least a similar) output by navigating to the motor  setup menu in QGC and then either clicking the switch to start the motor test, or by arming it with a configured button.

IMPORTANT NOTE:
This may be more of a QGC issue, but if you leave that menu and go back the main flight view, you will get the same error output when you arm the motors.

These observations are purely from SITL

**Comment by jaxxzer** [comment] 2019-07-15 22:24
@jaylthegreat You have encountered this: https://github.com/mavlink/qgroundcontrol/issues/7275#issuecomment-480306112

**Comment by Williangalvani** [comment] 2019-09-11 19:10
The issue is that QGC is able to get into a state where the motor test is not running in ardusub, but it tries to send motor test messages anyway. 

For example, if you stop the motor test and start again without waiting for the cooldown, the button will be able to arm the motors and send test messages, but ardusub will refuse to move them and reply with a Failure, which results in this:
![Screenshot from 2019-09-11 15-59-52](https://user-images.githubusercontent.com/4013804/64726538-41360200-d4ad-11e9-95b8-57546c18a55c.png)
![Screenshot from 2019-09-11 16-01-31](https://user-images.githubusercontent.com/4013804/64726635-76425480-d4ad-11e9-9223-bb743e2e3296.png)

This will be partially fixed by https://github.com/mavlink/qgroundcontrol/pull/7808

**Closed** 2019-09-27 20:16 UTC
Labels: Sub
