### ISSUE TITLE
SITL: sim_vehicle -I flag doesn't appear to be working

### ISSUE THREAD

**Issue by gmorph** [ArduPilot/ardupilot#3059] opened 2015-10-22 00:33 UTC
Looks like we can't run multiple instances of the simulation.  Probably a simple bug.

http://ardupilot.com/forum/posting.php?mode=reply&f=81&t=14080

Thanks, Grant.

**Comment by magicrub** [comment] 2015-12-12 00:25
I thought this was working, didn't @WickedShell talking about using it recently?

**Comment by WickedShell** [comment] 2015-12-12 12:43
I had a problem with location where the L was case sensitive and I was
using the wrong case....

**Comment by peterbarker** [comment] 2016-01-05 06:19
This is working no problems for me.  Just tested two ArduPlanes / one ArduPlane+one ArduCopter.

**Comment by fbalaban** [comment] 2016-01-19 14:03
Well, @gmorph said he managed to replicate it.. I'm not sure how @peterbarker you managed to make it work, but are you definitely sure it's the same case? I mean, have you tried to send two different waypoint files to the two instances and then check if they still have different paths? Maybe it does it on the second run? Btw, your two SITL, are by the same build? Maybe you are using two different clones?

**Comment by Jesse-Millwood** [comment] 2016-11-07 15:47
This works just fine for me. 
Once you start the instances, I found it a good check to look at what the output is just to make sure they are using two different udp ports (which increment with the instance switch)

**Comment by OXINARF** [comment] 2016-11-07 17:38
We have since changed to a Python script so it's possible it is now fixed.

@gmorph @fbalaban Are you still seeing this problem?

**Comment by fbalaban** [comment] 2016-11-07 18:57
Hi,
sorry but I had found a workaround and didn't follow the forum discussion which by the way has a changed link: http://discuss.ardupilot.org/t/sitl-multiple-instances-waypoint-files-are-broadcasted/6938/6.
I'm terribly busy, I cannot replicate it now or check if it's there. Please give me 3 or 4 weeks to get back to you. 

Thanks

**Comment by OXINARF** [comment] 2016-11-07 19:02
From that link it looks like the issue is in MAVLink and MAVProxy, not in ArduPilot.

@peterbarker You commented in that thread, can you confirm the problem isn't in ArduPilot?

**Comment by Jesse-Millwood** [comment] 2016-11-07 19:11
Sorry I misunderstood the problem since the original link wasn't going to the correct place. A while ago I had an issue where the port numbers weren't changing when you had multiple instances. This is is what I thought the issue was. But I do have this issue with the waypoint file being broadcast and re-writing the wp file for the other instances.

**Comment by peterbarker** [comment] 2016-11-10 00:12
@OXINARF I do not believe there to be any issues with SITL's -I parameter; the ardupilot binaries AFAIK increment their listen ports appropriately.

**Comment by OXINARF** [comment] 2016-11-10 01:46
Alright, this issue looks like to be linked but external to ArduPilot so I'll close this.

**Closed by OXINARF** 2016-11-10 01:46 UTC
Labels: SITL

**Comment by hatyar** [comment] 2017-12-07 16:02
so this is what I try:

dronekit-sitl copter-3.3 --home=32.1542,34.83246,54,0 --instance=2

And this is what I get:

bind failed on port 5760 - Address already in use

I thought the address it would bind to is: 5780!

**Comment by khancyr** [comment] 2017-12-07 16:52
you need at least copter 3.5 or master

**Comment by hatyar** [comment] 2017-12-07 19:17
Thanks!

What is master?

**Comment by magicrub** [comment] 2017-12-11 07:14
>What is master?

"Master" branch in git. It's the main development branch.
