### ISSUE TITLE
Copter: EKF3 still initialising pre-arm message when trying to arm with no compass (attempt2)

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#16094] opened 2020-12-18 00:47 UTC
This is a follow-up to issue https://github.com/ArduPilot/ardupilot/issues/15967 which may have actually been two separate issues one of which is now fixed.

The issue is that "EKF3 still initialising" may appear if both the compass and GPS are disabled.  I was able to reproduce the issue (once) on a CubeBlack by doing this:

- loaded master onto the board
- enabled EKF3 (EK3_ENABLE = 1, EK2_ENABLE = 0, AHRS_EKF_TYPE = 3)
- EK3_SRC1_POSXY 0 (None)
- EK3_SRC1_VELXY 0 (None)
- EK3_SRC1_VELZ 0 (None)
- EK3_SRC1_YAW 0 (None)
- COMPASS_USE/2/3 = 0

I've placed a replay log here: https://www.dropbox.com/s/g6pn8ijcg8jof5f/randy-ekf3-still-initialising-master-18Dec2020.bin?dl=0

![image](https://user-images.githubusercontent.com/1498098/102560560-d8105600-4115-11eb-9f47-b295f5717df8.png)

FYI @andyp1per

**Comment by andyp1per** [comment] 2020-12-18 07:26
@priseborough I can also still reproduce this. Happy to try and get a replay log if it will help.

**Comment by anbello** [comment] 2020-12-21 13:24
Here a log with master ArduCopter V4.1.0-dev (4dc5162d) on OmnibusNanoV6 LOG_REPLAY=1
It is visible both the EKF3 still initialising pre-arm message and YAW drifting

https://drive.google.com/file/d/1McLge3sId_26OQb7iSStFRMaKVcw70Bg/view?usp=sharing

**Comment by tridge** [comment] 2021-01-13 07:57
maybe we need this code in EKF3?
https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_NavEKF2/AP_NavEKF2_core.cpp#L610

**Comment by andyp1per** [comment] 2021-01-13 17:32
Looks like this fixes it for me! I have created a PR.

**Comment by priseborough** [comment] 2021-01-15 11:31
@rmackay9, further investigation of the log you posted shows the issue is that the vertical position innovations for the second EKF instance go outside the 1m limit set for on-ground operation. The inclusion of the patch from https://github.com/ArduPilot/ardupilot/pull/16314 does successfully reset this behaviour, see graph from replay below comparing vertical position (baro innovation) and estimted Z accel bias for the original [1] and replayed [101] EKF data.

![Screen Shot 2021-01-15 at 9 33 47 pm](https://user-images.githubusercontent.com/3596952/104714483-5c87e000-5779-11eb-8e9e-de952daffbdb.png)

There is step in the  baro before which does coincide with the change to BARO1_GND_PRES and a arming event. This does cause a jump in innovations which should be avoided, but this is not the underlying issue.

![Screen Shot 2021-01-15 at 9 45 28 pm](https://user-images.githubusercontent.com/3596952/104715714-0025c000-577b-11eb-9149-7edc525ec0ef.png)

I'll keep picking away at that log.

**Comment by andyp1per** [comment] 2021-01-17 12:14
So hopefully here is an example replay log with yaw drift:
[1 01-01-1970 00-00-01.zip](https://github.com/ArduPilot/ardupilot/files/5826038/1.01-01-1970.00-00-01.zip)

I also videoed it:
https://youtu.be/II8UmFjLNPM
Please ignore the de-sync and crash at the end - this is because of the high logging rate and sharing of the flash SPI bus

**Comment by andyp1per** [comment] 2021-02-12 13:02
@rmackay9 @priseborough here is a replay log with EKF3 and severe yaw draft on a copter without a compass. The copter has rotated by a full 180 by the end of the log. It was a little difficult to keep it airborne due to DPS310 baro issues:

[ek3.zip](https://github.com/ArduPilot/ardupilot/files/5971900/ek3.zip)

I also tried to do an EKF2 log for comparison, not sure its as good:

[ek2.zip](https://github.com/ArduPilot/ardupilot/files/5971906/ek2.zip)

**Comment by priseborough** [comment] 2021-03-13 11:00
@rmackay9 I've been through the log you shared with this issue and also replayed it and can't find an internal issue with the EKF for IMU0. The XKF4.SS is 65701 or 0001 0000 0000 1010 0101 which means the following  solution status flags are true which is consistent with the sensors being used.

        bool attitude           : 1; // 0 - true if attitude estimate is valid
        bool vert_vel           : 1; // 2 - true if the vertical velocity estimate is valid
        bool vert_pos           : 1; // 5 - true if the vertical position estimate is valid
        bool const_pos_mode     : 1; // 7 - true if we are in const position mode
         bool initalized         : 1; // 16 - true if the EKF has ever been healthy

However the EKF using the second IMU does drop to a solution status of zero due to the vertical position innovation exceeding check limits:

<img width="1075" alt="Screen Shot 2021-03-13 at 9 23 27 pm" src="https://user-images.githubusercontent.com/3596952/111027161-948e6500-8442-11eb-94e7-97a2475e24bc.png">

<img width="1023" alt="Screen Shot 2021-03-13 at 9 26 38 pm" src="https://user-images.githubusercontent.com/3596952/111027200-d4554c80-8442-11eb-8402-4a52de2d88d5.png">

Replaying with master shows that the error in the EKF using the second IMU does disappear after the automatic reset, so there have been changes made since the log was generated that improve this behaviour, eg:

<img width="1034" alt="Screen Shot 2021-03-13 at 9 41 50 pm" src="https://user-images.githubusercontent.com/3596952/111027525-ed5efd00-8444-11eb-8ebf-43ecdda18414.png">

Interestingly the second IMU has a significant Z accel bias error of 0.4 m/s/s, eg:

<img width="1043" alt="Screen Shot 2021-03-13 at 9 43 29 pm" src="https://user-images.githubusercontent.com/3596952/111027579-3616b600-8445-11eb-8ca1-656884a5129c.png">

Including the patch from https://github.com/ArduPilot/ardupilot/pull/16842 makes no difference to the replay using master.

**Comment by andyp1per** [comment] 2021-03-13 15:20
My issues appear to be fixed by https://github.com/ArduPilot/ardupilot/pull/16842

**Comment by priseborough** [comment] 2021-03-13 22:07
It looks like the source issue is the on ground not moving check used to constrain yaw drift when on ground and enable learning of the yaw bias before flight is too stringent for the noisier IMU's. I'm now in the process of enabling logging of the check metrics when required for each EKF instance and adding a parameter enabling it to be adjusted if necessary.

**Comment by priseborough** [comment] 2021-03-13 23:18
I've pushed a couple of additional patches to https://github.com/ArduPilot/ardupilot/pull/16842 which solve the failure of the second EKF in @rmackay9 's log to detect the on ground not moving condition. This adds a parameter enabling the sensitivity fo the test to be adjusted. @rmackay9 can you check if https://github.com/ArduPilot/ardupilot/pull/16842 resolves the issue with your board.

**Comment by priseborough** [comment] 2021-03-14 01:32
@andyp1per Your yaw spin issue was caused by the EKF trying to learn gyro biases when fusing in the 'fake' position measurements that are used to stop roll/pitch angle error buildup. Any axis aligned with the gravity vector is inherently unobservable unless an external source of horizontal position or velocity is being used . I've added a couple fo patches that fix this behaviour.

Here are obtained by replaying your log at commit https://github.com/ArduPilot/ardupilot/pull/16842/commits/dff864ae086e6b2b94b386a5bd92496a51d6da54

The replayed data [100] vs the original data [1] shows:

The EKF yaw angle is consistent with the observed yaw spin:

<img width="1066" alt="Screen Shot 2021-03-14 at 12 23 19 pm" src="https://user-images.githubusercontent.com/3596952/111054481-17560500-84c1-11eb-851f-296f26aa97cf.png">

The estimated yaw gyro bias doesn't keep building up:

<img width="1070" alt="Screen Shot 2021-03-14 at 12 23 13 pm" src="https://user-images.githubusercontent.com/3596952/111054494-2dfc5c00-84c1-11eb-843a-a400d5ef1ee5.png">

The X and Y gyro bias estimates look sensible:

<img width="1094" alt="Screen Shot 2021-03-14 at 12 23 08 pm" src="https://user-images.githubusercontent.com/3596952/111054501-3e143b80-84c1-11eb-9747-a9c0917209ae.png">
<img width="1052" alt="Screen Shot 2021-03-14 at 12 23 00 pm" src="https://user-images.githubusercontent.com/3596952/111054505-42d8ef80-84c1-11eb-8a81-4b291529f416.png">

**Comment by andyp1per** [comment] 2021-03-14 08:59
Oh very nice @priseborough - thanks so much!

**Comment by priseborough** [comment] 2021-03-26 10:16
Fixed by https://github.com/ArduPilot/ardupilot/pull/16842

**Closed** 2021-03-26 10:15 UTC
Labels: EKF
