### ISSUE TITLE
Copter: compassmot should use measured total earth mag field instead of a default value

### ISSUE THREAD

**Issue by Olivier-ADLER** [ArduPilot/ardupilot#396] opened 2013-06-28 13:54 UTC
When computing CompassMot interference level, we are using a default expected value (330) to compute the % interference level.

In some region of the world the total mag field is weaker, causing a lower reported Compassmot interference value.

It would be better to measure the total earth mag field value during compass calibration, and use this value during compassmot calibration for reporting interference level.

At the same time, during compass calibration, it could be desirable to report earth field inclination and total mag field stability.

Mag field stability will characterize the frame magnetic interference level.
Inclination will warn about a user located in a region of the world where inclination is very high, say between 80 and 90°.
In those regions, compass stability is not good enough for navigation purpose because the horizontal mag component is very small.

Those three values, inclination, total mag field and mag field stability,  could be useful for user support. They are important to diagnose mag field problems, the same importance as compasmot interference level.

**Comment by jmachuca77** [comment] 2018-07-17 15:06
@rmackay9 aren't we learning the compass motor offsets during flight now? Is compass-mot calibration still needed?

**Comment by rmackay9** [comment] 2019-01-18 01:52
@Naterater, we still have compassmot although it's not used that much anymore.  I suspect we will never fix this although the issue is valid.  It's really just a display issue at the end of the compassmot procedure, it doesn't affect the calibration results themselves... let's close it I guess..

**Closed by rmackay9** 2019-01-18 01:52 UTC
Labels: Copter
