### ISSUE TITLE
Add metadata for all SIM_ params

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#17134] opened 2021-04-10 12:34 UTC
**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by WickedShell** [comment] 2021-04-13 06:00
Closing as a duplicate of #2338

**Closed by WickedShell** 2021-04-13 06:00 UTC
