### ISSUE TITLE
Common: Implement Follow-me by Mavlink msg

### ISSUE THREAD

**Issue by lvale** [ArduPilot/ardupilot#3929] opened 2016-04-19 09:07 UTC
Now that the accorded Mavlink message has gone into Mavlink, we should think on implementation on Copter/Plane/Rover

https://github.com/mavlink/mavlink/pull/526/files

**Comment by lvale** [comment] 2018-08-19 22:38
Having this @rmackay9 would be a solution for the users that were using the broken Tower solution

**Comment by lvale** [comment] 2018-08-20 07:07
@peterbarker would enable a free alternative solution to use follow-me on mobile devices

**Comment by peterbarker** [comment] 2018-08-21 01:11
On Mon, 20 Aug 2018, Luis Vale Gonçalves wrote:

> @peterbarker would enable a free alternative solution to use follow-me on
> mobile devices

Sorry, I wasn't clear.

If Tower already supports these messages then yes, supporting those 
messages in AP would allow a follow-me.

However, if Tower doesn't already support those then it could just as 
easily support follow-mode by broadcasting its position and setting the 
parameters appropriately.

**Comment by lvale** [comment] 2018-08-21 02:04
Sorry I wasn't clear also.
QGC supports this now, and it could be an alternative on mobile devices.

**Comment by auturgy** [comment] 2019-01-27 09:13
No reason to close. It’s a valid enhancement request.

**Comment by rmackay9** [comment] 2019-09-30 23:23
I think this is a duplicate of this other issue so let's close it: https://github.com/ArduPilot/ardupilot/issues/8517

**Closed by rmackay9** 2019-09-30 23:23 UTC
Labels: AllVehicles, Enhancement
