### ISSUE TITLE
Plane: Stall Recovery switch 

### ISSUE THREAD

**Issue by geofrancis** [ArduPilot/ardupilot#3862] opened 2016-04-05 14:45 UTC
i  have been flying wings with apm recently and have been testing stall recovery and how to automate it.

when i would switch to stabilised and hold the nose up with no throttle it would go into a flat spin and spiral nose down until it crashed no matter how much throttle you gave it since it would keep trying to pull up. 

So after experimentation and lots of crashes i found the most reliable technique is to switch to acro mode for 2 seconds with the throttle at 100% then to RTL. this would stop it trying to pull the nose up long enough for it to stop the spin and pick up airspeed so when it switches to RTL it can pull the nose up and back to stable flight. 

I programmed this in opentx so when i hit the spring loaded trainer switch it recovered but it shouldnt be to hard to implement as a flight mode in arduplane so when you get stall detection working.

also if you assign an input for a stall sensor and just have a parameter for it so if its above a specific value then plane is stalled then it would let people design sensors that can be simply plugged in.

**Comment by magicrub** [comment] 2016-04-05 15:48
Sounds like you have a solution for your particular aircraft. We will need
to experiment with other vehicle body types to try and find a solution to
those which are most likely totally different behavior.

This is a duplicate of https://github.com/ArduPilot/ardupilot/issues/2669
so I am closing this issue but please post this info over there so we don't
lose your great flight test work.

**Closed** 2016-04-05 15:48 UTC
