### ISSUE TITLE
VISO_DELAY_MS has no effect

### ISSUE THREAD

**Issue by patrickpoirier51** [ArduPilot/ardupilot#20163] opened 2022-02-24 16:33 UTC
## Bug report

**Issue details**

Trying to sync the Visual Odometry signal with AHRS but it seems that the VISO_DELAY_MS has no effect
I initially tried with 15 Msec and I had about 200 Msecs, then I changed to 180 Msec and still see the same latency between signals

**NOTE : I am using OpticalFlow as well , would the OF DELAY might interfere ?**
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_NavEKF3/AP_NavEKF3_core.cpp#L41

**Version**
V4.2.0-dev

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quadcopter

**Hardware type**
CUBE ORANGE

**Logs**
_Please provide a link to any relevant logs that show the issue_
https://drive.google.com/file/d/1rB6Ac87E10Dfkf3vpwpvNQvXP-VOhTgw/view?usp=sharing

DELAY @ 12 msecs
![image](https://user-images.githubusercontent.com/12484190/155570932-61bfa47f-2c3d-45b0-8a85-6ed862536982.png)

Delay @ 180 msecs
![image](https://user-images.githubusercontent.com/12484190/155567480-831cffff-48fe-4794-ba09-09b54fc54666.png)

**Comment by rmackay9** [comment] 2022-02-24 22:54
I think the issue is just in expectations.  The lag doesn't affect when the sensor data is logged, it affects when the EKF fuses the data.  I'm pretty sure that the VISO_DELAY_MS parameter does have an impact because I worked with a partner to set this and it resolved issues they were seeing.

If you agree I think we should close this issue.

**Closed** 2022-02-24 23:33 UTC
