### ISSUE TITLE
Quadplane: Add PrecisionLand to Quadplane

### ISSUE THREAD

**Issue by ohitstarik** [ArduPilot/ardupilot#17069] opened 2021-03-31 18:45 UTC
Kind of wanted to bring attention to this again. The feature request is a port of precisionland into quadplane from Copter. 

I've tried some alternatives:

This has been (successfully) attempted by others but there's no stable implementation into ardupilot master, it's always fallen through the cracks at the last stages. Theres two previous attempts that I wanted to bring back to light and work on, but havent been able to make functional so I cant work on them. #10378 compiles and runs, but never gets a target lock. Arducopter from same firmware gets target lock no problems. #11339 builds, but the cubeBlack doesnt boot properly/run properly/send any mavlink messages. Thank you to these two devs for their work on it so far.

edit: Theres a 3rd implementation as well: https://github.com/ArduPilot/ardupilot/pull/13263. Just tried it and logs still dont show a target lock, compared it to the arducopter from the same firmware and that one shows target lock. Maybe these just dont have proper logging coded in?

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Comment by rmackay9** [comment] 2021-04-01 00:59
This is really a duplicate of an existing issue so closing: https://github.com/ArduPilot/ardupilot/issues/9415

txs for using AP!

**Closed by rmackay9** 2021-04-01 00:59 UTC
