### ISSUE TITLE
EKF Uncontrolled height, incorrect vertical velocity obtained from inertial navigation

### ISSUE THREAD

**Issue by lixiaowei123** [ArduPilot/ardupilot#25059] opened 2023-09-20 23:48 UTC
I recently encountered a problem where the altitude of the multi rotor drone is not controlled. From the logs, it can be seen that there is a problem with the vertical speed, but I don't know what caused it

**Comment by lixiaowei123** [comment] 2023-09-20 23:53
[log.zip](https://github.com/ArduPilot/ardupilot/files/12678538/log.zip)

**Comment by lixiaowei123** [comment] 2023-09-20 23:58
![1695254288511](https://github.com/ArduPilot/ardupilot/assets/16605202/4459d775-4fb5-4430-bb16-07c8a02380da)

**Comment by rmackay9** [comment] 2023-09-21 00:00
Hi @lixiaowei123,

It looks like high vibration when the throttle is raised.
![image](https://github.com/ArduPilot/ardupilot/assets/1498098/d85cf920-e74f-4e87-ada7-78e884aef139)

By the way, support questions should really go in the forums.  The issues list is for confirmed bugs or enhancement requests so I'll close this.  Sorry to be strict but if we're not then our to-do list just turns into a support forum.

**Closed by rmackay9** 2023-09-21 00:00 UTC

**Comment by lixiaowei123** [comment] 2023-09-21 01:30
@

> Hi @lixiaowei123,
> 
> It looks like high vibration when the throttle is raised. ![image](https://user-images.githubusercontent.com/1498098/269446084-d85cf920-e74f-4e87-ada7-78e884aef139.png)
> 
> By the way, support questions should really go in the forums. The issues list is for confirmed bugs or enhancement requests so I'll close this. Sorry to be strict but if we're not then our to-do list just turns into a support forum.

thank you,I feel that there may be a bug in the acceleration offset learning of EKF
![1695259844604](https://github.com/ArduPilot/ardupilot/assets/16605202/94b9981f-a029-4e5b-984b-27da6cc16ec9)
