### ISSUE TITLE
Question - Moving precisely without GPS

### ISSUE THREAD

**Issue by alexblack** [ArduPilot/ardupilot#4154] opened 2016-05-18 03:00 UTC
I'd like to be able to move and position the drone without GPS, I'm working on a visual positioning system that uses the camera to detect a target from which position can be determined.

I'm using `SET_POSITION_TARGET_LOCAL_NED` (through DroneKit) to move the drone (a 3DR Solo), and its generally working, but, the movements are not very precise, for example I attempted to move the drone 10cm, and it moved 48cm.

Questions:
1. Does `SET_POSITION_TARGET_LOCAL_NED` work without the use of GPS?
2. How should `SET_POSITION_TARGET_LOCAL_NED` be used for precise movements?

Currently I'm sending `SET_POSITION_TARGET_LOCAL_NED` every 100ms with a new velocity, on a curve, from 0 upto a max velocity and back to 0, where the integral of the curve is the distance I want to travel.

**Comment by alexblack** [comment] 2016-05-18 03:01
In particular altitude control seems poor, often it kinda of jumps up and down, could this be related to: http://diydrones.com/forum/topics/althold-inaccurate-altitude-estimation-and-motor-pulsing?xg_source=activity&id=705844%3ATopic%3A2170652&page=3#comments

**Comment by magicrub** [comment] 2016-05-18 03:22
You've posted a help question in the developer TODO list. Please re-post in
discuss.ardupilot.org

**Comment by rmackay9** [comment] 2016-05-18 03:23
It's also a duplicate of this one which I've answered.  https://github.com/ArduPilot/ardupilot/issues/4153

**Closed by magicrub** 2016-05-18 03:22 UTC

**Comment by alexblack** [comment] 2016-05-18 03:29
Hi Randy, oh, they're different questions, and I don't see an answer to the other one.. #4153 I asked where to find the source for SET_POSITION_TARGET_LOCAL_NED

**Comment by alexblack** [comment] 2016-05-18 03:29
Ok, thanks @magicrub
