### ISSUE TITLE
Pixhawk / Copter: segfault on connect via USB

### ISSUE THREAD

**Issue by sgofferj** [ArduPilot/ardupilot#1161] opened 2014-06-21 12:59 UTC
I just tried to connect and this happened:
Connect USB cable: Normal startup.
Start APM Planner, select /dev/ttyACM0, click connect
----> Pixhawk freezes (really freezes - LED stops blinking).

Debug console says:

Assertion failed at file:armv7-m/up_hardfault.c line: 184 task: ArduCopter
sp:     2000ffe4
IRQ stack:
  base: 20010050
  size: 00000ffc
2000ffe0: 2000ff44 2000ffe4 1000f418 00001ffc 0809613f 000000b8 080cc424
2000ff44
20010000: 080a41fd 2000ff44 08096215 00000010 08096419 080963fd 080a7355
2000d360
20010020: 00000003 08096375 080a4229 00000000 200102d8 adf92276 0000048f
080a3d8f
20010040: 1000f22c 00000000 08096375 2000ff44 10005130 00000001 00000000
00000000
sp:     080cc3cf
User stack:
  base: 1000f418
  size: 00001ffc
R0: 2000ffe8 08096165 080902ad 080cc3c3 00000004 00000000 080902cd 00000000
R8: 08096215 1000f22c 000000b0 08090299 080902ad 00000000 080cc3c3 00000004
xPSR: 00000000 BASEPRI: 00000000 CONTROL: 00000000
EXC_RETURN: 000000b0

Drones-discuss: https://groups.google.com/forum/#!topic/drones-discuss/CaQcQzD-tIM

**Comment by rmackay9** [comment] 2015-01-30 06:08
Lorenz has reported there was a NuttX bug to do with memcpy that could cause memory corruption and all the horrible things that can result from that.  We know it affected USB communication so perhaps this was the cause of this issue.

The NuttX fix will go out with AC3.2.1 and the next release of Plane.

If anyone is up to it, it might be good to test that we can't reproduce this anymore.

**Comment by sgofferj** [comment] 2015-01-30 06:11
I can do that as soon as I seem to have been most successful in reproducing it... Please write a comment in the issue when a testable release is out so I remember.

**Comment by geeksville** [comment] 2015-01-30 15:54
Alas.  Yesterday I tried a build with this great fix.  Unfortunately, USB
comms still die when connecting from my linux desktop to the PX4.

**Comment by hsteinhaus** [comment] 2015-01-30 18:22
Had an assertion fault just a minute ago while USB was connected and vehicle was supplied via battery. Multiple resets via FMU reset button resulted in the same crash. After dis/reconnecting battery and USB, I was no longer able to reproduce the fault. 

Software used: lastest PX4/Firmware with NuttX form the submodule (not the diydrones forks) and APM master, running UAVCAN ESCs and GNSS.

**Comment by LorenzMeier** [comment] 2015-01-31 15:08
@geeksville @hsteinhaus Could you please provide the exact GIT hashes for PX4/Firmware and PX4/Nuttx and confirm you ran distclean / make archives? I just want to be sure we're not chasing ghosts.

Also please try to avoid to just provide *it doesn't work* feedback. There is very little to go on and its not helping much to actually resolve the issue. I would appreciate if you could provide stack traces (and the associated ELF file) and a little more context. E.g. I don't even know if you had this issue before, if its specific to a particular computer, if you can reproduce 100% or not..

@geeksville Could you also please try these two: nuttx_bringup branch in PX4/Firmware. And this NuttX branch: https://github.com/PX4/NuttX/tree/usbupdate

**Comment by geeksville** [comment] 2015-03-08 01:23
I _finally_ figured out (sort of) why arducopter USB crashes every time
with my lenovo laptop (and how to reproduce it reliably).  My laptop has
two USB ports, one is USB3 the other is only USB2.  The USB2 port works
100% of the time, the USB3 port crashes 100% of the time (with current
master).  I have two USB3 hubs downstream of my normal USB3 port.  If I
plug in pixhawk into one of them it will die (stop talking serial -
investigated no further but can in a few weeks) but the other hub (also
USB3) pixhawk works fine with.

(this behavior was also true with the nuttx_bringup branch.  But currently
I'm using: APM: ArduCopter V3.3-dev (af7765c5)
APM: PX4: 3f083e02 NuttX: a164ab1b

**Comment by rmackay9** [comment] 2015-05-13 03:06
pushing to AC3.4.

**Comment by rmackay9** [comment] 2016-08-29 06:20
This is very old so I think I'm going to close it.  There have been some windows related USB improvements that have recently gone into master that may have improved the situation.

**Closed by rmackay9** 2016-08-29 06:20 UTC
Labels: BUG, Copter, Plane
