### ISSUE TITLE
Plane: create new flight mode - TAKEOFF

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#7182] opened 2017-11-05 12:47 UTC
Create new plane flight mode "TAKEOFF" that will:
- act like an AUTO mission executing NAV_TAKEOFF
- fly up to the RTL altitude (ALT_HOLD_RTL)
- then head home and loiter forever (like RTL_AUTOLAND=0 behavior)

**Comment by WickedShell** [comment] 2017-11-05 21:13
Duplicate of #2811 which has far more discussion.

**Closed by WickedShell** 2017-11-05 21:13 UTC
Labels: Enhancement, NeedToChangeGCS, Plane

**Comment by magicrub** [comment] 2017-11-07 02:30
THERE it is. I knew one was around but I couldn't find it. Thx.
