### ISSUE TITLE
MAVFTP can cause an autopilot reboot

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13536] opened 2020-02-10 08:07 UTC
I've found that I can cause the autopilot (a cube black) to reboot fairly easily using MAVFTP from Mission Planner.  The steps to recreate the issue are:

1. flash master onto the Cube Black (I was using "ArduCopter V4.0.3-dev 0cf747cd")
2. restore all parameters to their defaults
3. open Mission Planner and press Ctrl-X to connect using MAVFTP
4. attempt to open the APM directory

At this point the connection to the autopilot is lost.  MP goes on to print a nasty error message but this is another matter.

**Comment by WickedShell** [comment] 2020-02-10 20:05
Closing as duplicating #13085. I was unable to reproduce it on that one, but I will follow the steps listed here and see if that works better.

**Closed by WickedShell** 2020-02-10 20:05 UTC
Labels: BUG
