### ISSUE TITLE
IR Lock for ArduPlane

### ISSUE THREAD

**Issue by sazzal10** [ArduPilot/ardupilot#5072] opened 2016-10-26 19:20 UTC
Hello guys, I'm new to this great community.

I'm working on a project that requires precision landing for fixed wing planes.
Similar to the function already implemented in the ArduCopter, I want to use the Pixycam and a large infrared beacon to land the aircraft into a net. I have used this function on a quad and had no problems making it work great.

Currently, I have the aircraft flying very well using the Plane 3.6 firmware. My plan is to modify the existing plane firmware with the required ir lock/ precision landing code form the Copter firmware.

My question is, has anybody experimented with this before? What is required to "merge" the existing "Precision Landing" Copter parameter into the Plane firmware? I understand that the orientation of the sensor will be 90 degrees to whats normal on quads, but at the moment, I only want to add the parameter and compile the firmware with the required modules. (One step at a time)

I'm new to the ardupilot code but educated on how to compile, edit and upload a custom firmware to the autopilot.

Any tips would be well appreciated!
Edit: I see this question has been brought up before! I hope some else has some insight on it!

**Comment by magicrub** [comment] 2016-10-26 19:53
Thanks for your interest and support! In an effort to not fork discussions, I'm going to close this issue as a duplicate of https://github.com/ArduPilot/ardupilot/issues/2907 so we can stay focused on the discussion. I look forward to your work on this!

**Closed by magicrub** 2016-10-26 19:53 UTC
