### ISSUE TITLE
Better use of pulse width for RC channels above 6

### ISSUE THREAD

**Issue by tarantulito** [ArduPilot/ardupilot#14941] opened 2020-07-29 17:30 UTC
## Feature request
Assign several functions to RC channels for channel 7 on, supposing:
1-4: navigation and throttle.
5: flight mode change
6 (analog): camera position

**Is your feature request related to a problem? Please describe.**
Given above common channels functions assignment, upper channels seem to have a none/all asignment, losing many possible functions if taking advantage of all the different pulse widths (say 1000...2000 µs).

**Describe the solution you'd like**
Code the RCx_OPTION parameters similar to flight mode channel (normally 5, with six ranges), with at least four ranges:
-If assigned to a three position swith use low/mid/high values.
-If assigned to a mix between two two position switches use four pulse values.
-Ideally, as for flight mode change channel (six ranges).
For example, RC7_OPTION with a three position switch assigned to channel 7:
-Low: nothing (0).
-Mid: brake (33).
-High: motor emergency stop (31).
 
**Describe alternatives you've considered**
Sorry if this has been proposed elsewhere, or has been rejected, or I miss something. The actual coding for RCx_OPTION parameters does not take advantage of the whole range of pulse widths: one channel assigned to one function as none/all.

**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by rmackay9** [comment] 2020-07-29 22:48
I think this is a duplicate of issue https://github.com/ArduPilot/ardupilot/issues/4389 so I think I will close this.  Happy to re-open of course if I've made a mistake.

**Closed by rmackay9** 2020-07-29 22:48 UTC
