### ISSUE TITLE
Geofence - Inverting and combining to create a safe-zone “corridor” - Feature request

### ISSUE THREAD

**Issue by aercamti** [ArduPilot/ardupilot#5141] opened 2016-11-04 17:16 UTC
Hello,
I saw in the docs of Mission Planner that the new polygon GeoFence can be combined with the circular one, to create certain boundaries.

We are doing inspections which involve towers, and need to circle them (with automated flight plans), sometimes in tight areas, with other obstacle sticking up (other towers, buildings).

To increase flight safety, it would be great to have an additional, "inverted" fence which defines a "no-go area" - INSIDE the outer GeoFence. This should thereby create a corridor in which safe movements can happen without a chance of
collision. Ideally, even multiple "inverted" fences should be definable, to avoid additional obstacles.

Having such an additional fence could avoid some serious mishaps (i.e. inadvertently hitting the tower…)

Ideally a RTL path would also be smart enough to circumvent the inner, "inverted" fence, while still making it Home or to a Rally Point. It should "hug" an encountered inner fence on the RTL path, and fly around it in a definable distance.
Once the path is clear, it can fly straight to Home.

Example of outer geofence with inner ones: 
![70277673dd9b2df94c3d952562201fcf1e832c17](https://cloud.githubusercontent.com/assets/23265147/20015109/38f4914c-a2ba-11e6-8d96-44f54ca44323.png)
(Having posted that on the Ardupilot forum, I was asked to submit it here instead, and have read that as such it has been discussed already. Unfortunately I do not have sufficient programming skills to be of any help :-( )

**Comment by OXINARF** [comment] 2016-11-04 18:17
Yes, like Tom said, this is a duplicate of #391. #1056 is also related.

**Closed by OXINARF** 2016-11-04 18:17 UTC
