### ISSUE TITLE
Copter: extend RCMap to cover at least channel 6 (maybe all channels up to 8)

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#685] opened 2013-11-14 03:23 UTC
Some transmitters have limits on what mixing can be done on some channels.  Request from Dragu MIhai.

This would also allow trad heli users to get by with a 6 or 7 channel transmitter instead of 8.

**Comment by WickedShell** [comment] 2017-02-10 05:28
@rmackay9 I don't know enough about copters, but isn't this covered with the servo changes that went in? I thought that got all vehicles arbitrary channel remapping...

**Comment by rmackay9** [comment] 2017-02-10 06:00
@WickedShell, I don't think so.  Tridge's servo changes separated min/max for input/output but the improvements that adds are mostly on the output side of things.

**Comment by auturgy** [comment] 2018-05-15 22:32
@peterbarker can this be closed now?

**Comment by peterbarker** [comment] 2018-05-16 01:01
On Tue, 15 May 2018, auturgy wrote:

> @peterbarker can this be closed now?

Not until the channel-option patch stuff is merged.

**Comment by amilcarlucas** [comment] 2018-10-19 21:47
Channel option patch is merged now AFAIK. Can this be closed now ?

**Comment by peterbarker** [comment] 2018-10-19 22:01
@amilcarlucas I'm actually a bit confused by it, actually.  rcmap says "to find the throttle look at channel 3".

e.g.
`param set RCMAP_THROTTLE 3`

So extending it to higher channels doesn't make sense.  Now adding more options in there (`RCMAP_XYZZY`) might be what it's getting at.  That wouldn't be covered by the channel-options patch.

My "eliminate RCMAP" PR https://github.com/ArduPilot/ardupilot/pull/8307 would *definitely* cover whatever this issue about :-)

**Comment by WickedShell** [comment] 2018-10-19 22:50
The point of the issue (I believe) is that copter has those switch functions for channel 6/7/8 such as motor interlock/autotune and the user wants to map that onto a different channel from their transmitter.

**Comment by rmackay9** [comment] 2018-10-19 23:09
I don't mind if this is left open until #8307 goes in or is closed now.. one way or the other we're definitely not going to extend RCMAP..

**Comment by auturgy** [comment] 2023-01-27 06:33
This is overtaken by events.  The specific solution has not been implemented but the problem is solved.

**Closed by auturgy** 2023-01-27 06:33 UTC
Labels: Enhancement, Copter
