### ISSUE TITLE
HoTT Telemetry

### ISSUE THREAD

**Issue by Ralfde** [ArduPilot/ardupilot#5912] opened 2017-03-20 14:01 UTC
#### Issue details
HoTT telemetry was there in some older versions, but with the actual versions it's still not available as a choice in the Mission planer.
Is there anyone, who could implement it again?
I really wonder, because the HoTT Text mode would allow also really easy settings of PIDs and other things without the use of a PC. Does one of the developers have interest to implement it again? 

#### Version
3.4.6

#### Platform
[ X ] All
[  ] AntennaTracker
[ X] Copter
[  ] Plane
[  ] Rover

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Quadrocopter
#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_
Pixhawk
#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by OXINARF** [comment] 2017-03-20 19:50
Duplicate of #856

**Closed by OXINARF** 2017-03-20 19:50 UTC
