### ISSUE TITLE
Arducopter flips on manual landing in position hold

### ISSUE THREAD

**Issue by kosmikkosmik** [ArduPilot/ardupilot#3915] opened 2016-04-17 15:09 UTC
#### Issue details

When doing manual landing in Position Hold after touching the ground sometimes two motors start to spin at higher speed and copter rolls over. This doesn't happen when landing in RTL mode.
For some time I managed to workaround it by quickly switching to Stabilize mode after copter touching the ground, but this time it flipped very quickly so when I selected Stabilize it was too late.
#### Version

ArduCopter built from master branch, but I had the same issue with 3.3
#### Platform
- [ ] All
- [ ] AntennaTracker
- [X] Copter
- [ ] Plane
- [ ] Rover
#### Airframe type

Quadrotor, DJI F450
#### Hardware type

Pixhack (pixhawk clone)
#### Logs

https://onedrive.live.com/redir?resid=5591523E73255C49!122162&authkey=!AGFBH6gvPfmpYQ8&ithint=file%2clog

**Comment by lthall** [comment] 2018-01-11 06:50
The logs do not show the tip over being caused by the attitude controller. Without more info and given the age of this issue I am closing it.

**Closed by lthall** 2018-01-11 06:50 UTC
Labels: Copter
