### ISSUE TITLE
Copter: Loiter tends to "freight train" when you increase the maximum velocity.

### ISSUE THREAD

**Issue by jschall** [ArduPilot/ardupilot#1458] opened 2014-10-10 04:01 UTC
The loiter controller is essentially a simple simulation of a perfect copter in alt hold.

So by necessity, drag must be at equilibrium with acceleration input when the copter is at the maximum speed. This means that setting the maximum speed higher means either decreasing drag or increasing the acceleration input.

I would suggest that we make maximum acceleration configurable or make it a function of maximum velocity. At one point I think there was a parameter "WPNAV_LOIT_ACCEL" but it doesn't seem to be in master.

**Comment by R-Lefebvre** [comment] 2015-05-15 20:27
Pretty sure this is completed.

**Comment by rmackay9** [comment] 2015-05-17 01:34
Jonathan has added some additional parameters and changes that allow us to reduce this but we haven't actually tested (in master) that it doesn' freight train anymore.. in fact, I think it still does unless we come up with better defaults for those new params.

**Comment by R-Lefebvre** [comment] 2015-05-17 01:56
I'm OK with it freight training if that's the intended behaviour.  My complaint was because I didn't understand.  And now we can change those params.  I'll confirm, but I think this is good now.

**Comment by rmackay9** [comment] 2015-05-17 04:00
Ok.  One thing that I saw from Jon's solo branch was that the loiter jerk limit had to be increased from 17m/s/s to 40 (or something like that).  I don't know if that's necessary or unrelated but it went in at the same time.  Feel free to ask Jon about that.

**Comment by rmackay9** [comment] 2016-08-29 06:57
Ok, this is resolved so closing.  The need to document this is in the above linked issue.

**Closed by rmackay9** 2016-08-29 06:57 UTC
Labels: Copter, Enhancement
