### ISSUE TITLE
QGC SurveyScan support via MAV_CMD_DO_SET_ROI_WPNEXT_OFFSET

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot#10820] opened 2019-03-15 02:49 UTC
QGroundControl allows [StructureScan](https://docs.qgroundcontrol.com/en/PlanView/pattern_structure_scan.html) via "generic MAVLink", but there is a note at the top of the documentation:
![image](https://user-images.githubusercontent.com/5368500/54404826-d20f6900-4728-11e9-8534-b6fe33e036c3.png)

According to https://github.com/mavlink/qgroundcontrol/issues/6824 the issue is that `MAV_CMD_DO_SET_ROI_WPNEXT_OFFSET` has not been implemented.

Clearly it is desirable for ArduPilot if this this feature can be supported.

**Platform**
[ X ] Copter
[ X ] VTOL

**Comment by rmackay9** [comment] 2019-03-15 03:16
This might be a duplicate of this issue [command here](https://github.com/ArduPilot/ardupilot/issues/7658).

**Closed** 2019-03-15 03:41 UTC

**Comment by hamishwillee** [comment] 2019-03-15 03:43
Yes, it is, or will be solved by that issue. I searched for MAV_CMD_DO_SET_ROI_WPNEXT_OFFSET, and survey scan, so sorry, missed that.
