### ISSUE TITLE
AC_WPNav: bad heading occurs during large vertical distance difference

### ISSUE THREAD

**Issue by lukezhqin** [ArduPilot/ardupilot#15311] opened 2020-09-11 07:36 UTC
#15310 Bug report

**Issue details**

Here is the story goes like:
I once done a mission fly with my drone but set poor wrong altitude of 300 instead of 30m in one waypoint. The drone tookoff correctly but began to locking head to this wrong altitude waypoint. I command my drone back then. I understand that the controller would perform well to keep a very small horizotal speed under this condition because so large distance compared to diference in xy-axis. But this might just be the true reason to this strange problem.

Digging into the code in AC_WPNav.cpp from line 511-523:

> 

    // update the target yaw if origin and destination are at least 2m apart horizontally
    if (_track_length_xy >= WPNAV_YAW_DIST_MIN) {
        if (_pos_control.get_leash_xy() < WPNAV_YAW_DIST_MIN) {
            // if the leash is short (i.e. moving slowly) and destination is at least 2m horizontally, point along the segment from origin to destination
            set_yaw_cd(get_bearing_cd(_origin, _destination));
        } else {
            Vector3f horiz_leash_xy = final_target - curr_pos;
            horiz_leash_xy.z = 0;
            if (horiz_leash_xy.length() > MIN(WPNAV_YAW_DIST_MIN, _pos_control.get_leash_xy()*WPNAV_YAW_LEASH_PCT_MIN)) {
                set_yaw_cd(RadiansToCentiDegrees(atan2f(horiz_leash_xy.y,horiz_leash_xy.x)));
            }
        }
    }

After checking the code blame history, I believe you guys have carefully improved the performace in Auto mode by this commit  #6143, but which would just induce this problem. We cannot achieve enough long `_leash` in horizontal axis to fulfill the conditions mentioned in the commit before, so I solve this problem in this PR #15310. Please kindly help to merge it, thanks a lot.

Please see some SITL screenshots here, which show significant differences between vehicle heading and GPS course: 
![WP1](https://user-images.githubusercontent.com/26009293/92884325-51781880-f444-11ea-8c85-b3574a8f605a.png), ![WP2](https://user-images.githubusercontent.com/26009293/92884373-5e950780-f444-11ea-8e19-6eee9b3b1e69.png), ![WP3](https://user-images.githubusercontent.com/26009293/92884405-6785d900-f444-11ea-8a32-cad322572e0d.png), [param:WP_YAW_BEHAVIOR](https://user-images.githubusercontent.com/26009293/92884444-6eace700-f444-11ea-9ec9-072b06c01c76.png)

**Version**
_master and V4.0.0 or maybe all released tags_

**Platform**
[  ] All
[  ] AntennaTracker
[×] Copter
[  ] Plane
[  ] Rover
[  ] Submarine
Same problem maybe occurs on other platforms also.

**Airframe type**
QUAD, hex, Y6, octa etc

**Hardware type**
Pixhawk, Cube

**Logs**
_log BIN file would be uploaded later if necessary still_

**Comment by rmackay9** [comment] 2020-09-11 23:21
Thanks for this detailed analysis.  Top priority at the moment is getting s-curves into master and hopefully we will have a PR ready for review in a week or two.  I hope this will solve the problem albeit in a different way.

**Comment by IamPete1** [comment] 2021-08-16 14:09
I cant reproduce this on master, must have been fixed by Scurves. @lukezhqin please re-open if you can find a mission that will cause this.

**Closed by IamPete1** 2021-08-16 14:09 UTC
