### ISSUE TITLE
GPS Arming Check is ignored in Stabilize mode 

### ISSUE THREAD

**Issue by 4sfaloth** [ArduPilot/ardupilot#5808] opened 2017-03-03 16:20 UTC
I am currently using Copter version 3.4.4 and noticed something which I believe must be a bug.

If I have the GPS arming check enabled and have no GPS fix, I am still able to arm my Copter in Stabilize mode if GeoFencing is disabled. I realize Stabilize mode does not require GPS, but since I enabled the GPS arming check certainly it should not let me arm it without a fix? 
This seems like a safety issue to me

**Comment by OXINARF** [comment] 2017-03-03 17:51
This is by design, the GPS isn't checked in modes that don't need it. There has been discussions about adding another parameter that enables GPS checks for all modes but it hasn't been done so far.

As we are aware of it, there are other related issues already open and our list of issues is big enough, I'm going to close this.

**Closed by OXINARF** 2017-03-03 17:51 UTC
