### ISSUE TITLE
Copter is departing with wrong yaw on first switch to AUTO

### ISSUE THREAD

**Issue by hsteinhaus** [ArduPilot/ardupilot#9868] opened 2018-11-20 20:09 UTC
### Bug report
With WP_YAW_BEHAVIOR set to 3 (face along GPS course), the copter is flying to it's first waypoint (and probably beyond) with wrong/random yaw attitude after an airborne start of the mission (from Loiter or PosHold). After switching back to Loiter or PosHold and then back to Auto again, the copter turns into the correct yaw attitude and continues it's mission normally and as planned.

![screenshot from 2018-12-08 21-22-50](https://user-images.githubusercontent.com/3057137/49690357-ae3bf600-fb2f-11e8-9d04-29bcecd15731.png)

**Version**
tested with 3.6.2-rc2, but I remember to see this bug since years

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad

**Hardware type**
mRo PixRacer

**Logs**
https://www.dropbox.com/s/ugi12jmbjx0atrk/00000003.BIN?dl=0

**Comment by rmackay9** [comment] 2018-12-10 01:41
I tried to reproduce this in SITL but couldn't immediately.  Of course that doesn't mean there isn't a problem just that I couldn't reproduce it.  The logs do look like there's a problem.  I would have expected ATT.DesYaw, ATT.Yaw and GPS.GCrs to all line up as long as the pilot hasn't provided any yaw input.  For much of the log this is true but it's not around lines 425000 to 550000.

**Comment by hsteinhaus** [comment] 2018-12-10 08:59
I think I have hundreds of similar logs on six different platforms (px4-v2,3,4 and fmuv2,3,4), the reproducability on real hardware is IMHO 100% since at least Copter 3.4.

Did you enter AUTO from PosHold?

**Comment by hsteinhaus** [comment] 2019-04-01 18:02
@rmackay9 It seems to be important to come from PosHold to corrupt the departure direction. When coming from Loiter, there is no such effect even in real world. From PosHold, I can reproduce it by a chance of nearly 100%.

**Comment by rmackay9** [comment] 2019-04-01 23:56
@hsteinhaus, ok, txs for the update

**Comment by IamPete1** [comment] 2021-08-29 17:58
I cant replicate when switching form PosHold, I suspect that this has been fixed with the change to Scurves. @hsteinhaus any update? Have you seen this on 4.1?

**Comment by IamPete1** [comment] 2021-09-11 17:14
Please re-open if this is still a issue.

**Closed by IamPete1** 2021-09-11 17:14 UTC
Labels: ClosePending
