### ISSUE TITLE
copter 3.5.7 LIS3MDL on external compass no work

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#8956] opened 2018-07-19 09:40 UTC
hello HMC5883L is EOL now, and all ardupilot hardware manufacturing companies change the old HMC5883L by the LIS3MDL.

I plugged new gps from drotek that include this new magnetometer, and it seems to be not handeled by copter 3.5.7....

using original pixhawk board (3dr iris).

**Comment by proficnc** [comment] 2018-07-19 10:12
No, not all hardware manufacturers are Diy this, we are removing the LIS3MDL as well from the Here, and moving to the icm20948 which has the ak09916 inbuilt

**Comment by auturgy** [comment] 2018-07-19 10:12
Can you provide more details? Which firmware (nuttx or ChibiOS), a log, etc. The LIS3MDL is definitely supported (although it too is EOL).

**Comment by rmackay9** [comment] 2018-07-19 10:44
The LIS3MDL is supported in Copter-3.5.7 but I can imagine two possible reasons it's not found:

- the COMPASS_TYPEMASK parameter has been set to a non-zero value (try making it "0")
- the -v2 version of the firmware is being loaded by default by the ground station.  Try specifically downloading and then uploading "ArduCopter-v3.px4" from [this directory](http://firmware.ardupilot.org/Copter/stable/PX4/).

**Comment by rmackay9** [comment] 2018-07-19 10:46
I'm closing this because really it's a support issue, not a confirmed bugs or enhancement request.  This issues list is the to-do list for the developers and we need to be strict about this or it turns into another support forum and the devs will lose track of all they need to do.

**Closed by rmackay9** 2018-07-19 10:46 UTC
