### ISSUE TITLE
how quadplane use single copter frame mode

### ISSUE THREAD

**Issue by cudnn** [ArduPilot/ardupilot#4784] opened 2016-09-05 06:41 UTC
#### Issue details
_Please describe the problem, or desired feature_

#### Version
_What version was the issue encountered with_

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by magicrub** [comment] 2016-09-05 07:56
The title of the issue sounds like a help question and the content of the issue is the stock untouched template. Closing. Please use discuss.ardupilot.org for help questions.

**Closed by magicrub** 2016-09-05 07:56 UTC
