### ISSUE TITLE
Rover: compensate for asymetric thrust from propellers. 

### ISSUE THREAD

**Issue by geofrancis** [ArduPilot/ardupilot#19368] opened 2021-11-25 22:46 UTC
When testing Arduboat I ran into a problem where the controller doesn't take into account the difference in thrust when running a propeller forwards vs reverse. The result is when trying to yaw the boat with a tank steering left and right motor configuration the boat will shoot forwards, performing a wide circle rather than turning on the spot since the inboard motor that's running in reverse just can't overcome the thrust of the forward running propeller. This is more noticeable the narrower the boat since there is less leverage. The way I compensated for it was to just limit the forward thrust using the pwm limits, but with Dshot that doesn't work any more, and it still restricts total forward thrust. 

I tried testing with the current limiters set on the ESCs but they are using the same amount of power forward and reverse proving the difference in thrust is due to the difference in efficiency of the propellers running forwards vs reverse, so the result is it was still going forwards. 

What is needed is a percentage setting for how much of maximum forward thrust is used when turning with the left and right motors.

**Comment by rmackay9** [comment] 2021-11-30 00:28
I think this is a duplicate of https://github.com/ArduPilot/ardupilot/issues/8800

**Comment by geofrancis** [comment] 2021-11-30 01:12
> I think this is a duplicate of #8800

Its related, #8800 is describing controlling a vehicle with a asymmetric throttle/reverse speed range. with extra limits for reverse,  augmenting the speed control of a vehicle that can go backwards and forwards, its not for augmenting steering control on a skid steer boat.  for this issue we only need the limits when steering, general back and forward speed control is not the issue.

**Comment by geofrancis** [comment] 2022-07-07 09:43
I just found a case where this is a real problem. When testing bendy ruler the vehicle wants to hold position and rotate so it can scan for a path, that won't be possible if it can't stay still and turn at the same time because it will shoot forward if it tries.

**Comment by geofrancis** [comment] 2022-09-25 20:32
I have seen reports from in the wild now of people having real problems trying to rotate on the spot and have had to 3d print symmetrical propellers to compensate.

**Comment by rmackay9** [comment] 2023-09-06 03:48
This is include in 4.4.0-beta6 so I will close this now, thanks!

**Closed by rmackay9** 2023-09-06 03:48 UTC
Labels: Enhancement, Rover

**Comment by geofrancis** [comment] 2023-09-06 12:29
thank you!
