### ISSUE TITLE
Setting servo function to GPIO appears as if setup but will fail if attempted without BRD_PWM_COUNT

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#14558] opened 2020-06-08 15:47 UTC
This is a user issue, since he can set the SERVOx_FUNCTION to one needing BRD_PWM_COUNT changes to function, but gets no warning, either from Ardupilot or Mission Planner...is it worthwhile to have a check to see if functions are set needing GPIO functionality if they occur on  outputs beyond BRD_PWM_COUNT?
**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by IamPete1** [comment] 2021-08-08 14:32
@Hwurzburg I think we can close this now `BRD_PWM_COUNT` is gone? We also found that some were using this config by design when mapping to can servos.

**Closed** 2021-08-08 16:43 UTC
