### ISSUE TITLE
pwm value exceed 2000(rover)

### ISSUE THREAD

**Issue by oceangis** [ArduPilot/ardupilot#5958] opened 2017-03-30 11:02 UTC
#### Issue details
i use rover 3.1.2 and send pwm value though mavlink by joystick that pwm value was calibrated to 1000-2000. when i push to the maximum throttle,the pwm value of channel 1 and 3 displayed is about 2250.

#### Version
rover 3.1.2

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[ × ] Rover

#### Hardware type
pixhawk

**Comment by khancyr** [comment] 2017-03-30 14:18
Hello, Yes we are aware of this bug, we are working on a fix : see https://github.com/ArduPilot/ardupilot/pull/5819 (If you are only using rover, it should be safe to appy those fix while we are merging them into master)

**Comment by oceangis** [comment] 2017-03-30 14:28
Hi, khancyr 
    Thank you very much.

**Comment by OXINARF** [comment] 2017-03-30 14:56
This is a duplicate of #5817, closing.

**Closed by OXINARF** 2017-03-30 14:56 UTC
Labels: BUG, Rover
