### ISSUE TITLE
Copter: Logging Failure if "LOGS" Folder Not Present

### ISSUE THREAD

**Issue by SUI-Eric** [ArduPilot/ardupilot#16834] opened 2021-03-07 01:06 UTC
## Bug report

**Issue details**

If the LOGS folder is not present on an SD card, Ardupilot seems to have lost the ability to create that directory. This results in "Logging not started" pre-arm errors if using a new SD card or if the LOGS folder has been destroyed for any reason.

**Version**
4.0.6 & Later

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad

**Hardware type**
Cube Black & Cube Blue (F4)

**Logs**
Unavailable by definition. However, this issue is easy to reproduce by the below process:

1. Load a Cube with AC 4.0.6 or 4.0.7
2. Insert a blank SD card or manually delete the LOGS folder from a previously used SD card
3. Ensure logging is part of the arming checks
3. Attempt to arm

**Comment by amilcarlucas** [comment] 2021-03-08 09:09
I think tridge fixed this in master. @SUI-Eric can you test that?

Should the fix be backported? I do not think it is that important to grant a new release.

**Comment by SUI-Eric** [comment] 2021-03-08 17:23
@amilcarlucas I just grabbed the latest build of Master for Copter, and still experience "PreArm: Logging failed" if the SD card doesn't already have the LOGS folder present.

I do think it'd be important to backport the fix when it occurs, as any user who's got a new FC (or just a new SD card) and loads stable will experience it and not know why unless they check here.

**Comment by rmackay9** [comment] 2021-03-09 01:43
I was unable to reproduce this issue using Copter-4.0.7 on a CubeBlack or a CubeOrange.  I'm not saying that there's isn't a problem of course, just saying that I couldn't reproduce it.

**Comment by SUI-Eric** [comment] 2021-03-09 15:53
Interesting. I did some more testing and found that I have one Cube Black (out of four tested so far) that does not seem to be affected and creates the folder each time. The other three reliably reproduce this issue across several SD cards. 

I'll try a Matek board or something to try and determine whether this happens to somehow be a Cube problem instead of a bug.

**Comment by amilcarlucas** [comment] 2021-03-09 16:16
Same bootloader and FW version?

**Comment by WangLouis** [comment] 2021-07-06 07:02
Version 4.1.0  Copter Pixhawk4 mini using a new SD card don't create  LOGS folder.
pre-arm error massage is logging failed.

but using Version 4.0.3 CubeBlack can create  LOGS folder.

**Comment by IamPete1** [comment] 2021-08-16 16:02
related to https://github.com/ArduPilot/ardupilot/issues/16103 ?

**Comment by IamPete1** [comment] 2021-11-16 14:01
Closed by https://github.com/ArduPilot/ardupilot/pull/19267 and https://github.com/ArduPilot/ardupilot/pull/19271

**Closed by IamPete1** 2021-11-16 14:01 UTC
Labels: BUG, Copter
