### ISSUE TITLE
Plane: motor may unexpectedly power-up when flight controller rebooted

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#8187] opened 2018-04-18 11:44 UTC
I am not an experienced plane user but I had the main motor on my nano talon fire up as I rebooted the flight controller.  This is the sequence of events:

- vehicle was in Manual mode and disarmed
- transmitter throttle was at mid (it is a transmitter with a sprung throttle)
- rebooted the flight controller
- motor spun up for a few seconds (luckiliy the props were off)

**Comment by juvinski** [comment] 2018-04-18 11:59
How much is the value of your esc mid pwm and how much is your controller sending esc ?

**Comment by juvinski** [comment] 2018-04-18 12:01
I had similar behavior and was the pwm neutral - the radio was sending 1455 instead the 1500 configured on the esc and every boot the motor was spinning - first I tried to decrease rc3_trim to 1455 and after to 1555 to match the correct value

**Comment by rmackay9** [comment] 2018-04-18 12:03
@juvinski, The ESC's range is about 1000 ~ 2000 pwm (i think) with 1000 being off.  My transmitter was sending in mid throttle (about 1500pwm) so the issue is likely that as the main CPU on the Pixhawk is rebooted the I/O boards starts passing through the pilot's throttle to the ESC.  My feeling is that if we receive a reboot command (via mavlink), if the vehicle is disarmed then before rebooting we should put the I/O board in a state that the motors will not spin-up.

I don't know plane well though so this is just my feeling.

**Comment by Naterater** [comment] 2018-04-18 20:15
1st question: What is your RC3_Trim set to? Is it mid, or is it = RC3_Min?

2nd question: Should we be recommending that users with a "sprung" throttle use only half of the throttle range? (AKA, RC3_Min = 1500) Sprung throttles actually work well for reverse-thrust planes.

**Comment by WickedShell** [comment] 2018-04-26 03:57
Duplicate of #7005

**Closed by WickedShell** 2018-04-26 03:57 UTC
Labels: Plane
