### ISSUE TITLE
Plane: add support for multiple airspeed sensors

### ISSUE THREAD

**Issue by expntly** [ArduPilot/ardupilot#7479] opened 2018-01-03 01:16 UTC
#### Issue details
This is a feature request :-)

Since airspeed sensors / pitot tubes are pretty crucial for fixed wing flights and that a malfunction will very likely lead to a crash, it would be great to add support for multiple airspeed sensors.

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Comment by magicrub** [comment] 2018-01-03 01:34
Closing, duplicate of https://github.com/ArduPilot/ardupilot/issues/6670

**Comment by WickedShell** [comment] 2018-01-03 01:34
Worth noting the PR for this is #7174 and already submitted.

**Closed by magicrub** 2018-01-03 01:34 UTC

**Comment by magicrub** [comment] 2018-01-03 02:08
ahh yes, there it is. I thought there was a PR about that!
