### ISSUE TITLE
BRD_IMU_TARGTEMP seems broken in latest master. IMU heating does not stop...

### ISSUE THREAD

**Issue by pompecukor** [ArduPilot/ardupilot#11841] opened 2019-07-18 16:54 UTC
### Bug report

BRD_IMU_TARGTEMP seems to no longer limit heated IMU on Pixhawk2.1

Set it today on 45C and it continued to heat it (in doors air-conditioned room) till I disconnected battery at 69C

Verified by third party, so not my HW/Cube fault. I.E. Tested on other Cube.

_Please describe the problem_

**Version**
Latest master of Arduplane

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Hardware type**
Pixhawk Cube

![image](https://user-images.githubusercontent.com/31744367/61476293-002ddf80-a98d-11e9-99f6-c48cb61b0938.png)
![image](https://user-images.githubusercontent.com/31744367/61479171-8816e800-a993-11e9-8362-00ec110f47de.png)

![image](https://user-images.githubusercontent.com/31744367/61476441-60248600-a98d-11e9-8f0c-15c931702be2.png)
Obviously not full log, just showing how fast it is heating, so not any ambient effect.
BRD_IMU_TARGTEMP=45

**Comment by tridge** [comment] 2019-07-19 00:23
there was a change made to the detection of the polarity of the heater pin by @bugobliterator recently. I have assigned this issue to him

**Comment by WickedShell** [comment] 2019-07-19 05:08
FWIW I can't reproduce this with master as of yesterday. (On plane and a green cube)

**Comment by pompecukor** [comment] 2019-07-20 21:34
> 
> 
> FWIW I can't reproduce this with master as of yesterday. (On plane and a green cube)

Seems very  intermittent, even I find it hard to reproduce on the same Cube. As soon as we removed it from the UAV. However it is real. Have had a couple of confirmations form others, including as you may have seen even Randy experienced this on one of his units.

**Comment by proficnc** [comment] 2019-07-20 23:17
Do you have a log from the original report?
I’m interested to see the temperature on baro 1 vs baro 2
There is a significant self heating on the STM32, the key is to see if the heater was on, or if it’s self heat

**Comment by pompecukor** [comment] 2019-07-20 23:40
> Do you have a log from the original report?

Sorry Philip, I did not have logdisarm enabled. And as mentioned this was office testing. I may have tlog, will have to check Monday on office computer.

**Comment by pompecukor** [comment] 2019-07-20 23:57
I could access the office PC. only tlogs. I did a quick replay. In this case it was set to 45C. Here is from time of startup till over 70C. Roughly a 30min interval.
Was not completely cold from the start, as was already playing around with it before this, but I think you will get the idea. This is chronological obviously.

![image](https://user-images.githubusercontent.com/31744367/61585377-7469ae00-ab5a-11e9-8164-0022c2ac977e.png)

![image](https://user-images.githubusercontent.com/31744367/61585379-80557000-ab5a-11e9-9d37-4f91192066cc.png)

![image](https://user-images.githubusercontent.com/31744367/61585380-8cd9c880-ab5a-11e9-9e2e-429ad85e0ae0.png)

![image](https://user-images.githubusercontent.com/31744367/61585384-97945d80-ab5a-11e9-9290-630b2c4d1b0a.png)

![image](https://user-images.githubusercontent.com/31744367/61585385-9e22d500-ab5a-11e9-929f-09f7e9477f12.png)

![image](https://user-images.githubusercontent.com/31744367/61585388-a4b14c80-ab5a-11e9-9614-50871900cebb.png)

**Comment by pompecukor** [comment] 2019-07-21 00:11
![image](https://user-images.githubusercontent.com/31744367/61585494-d4f9ea80-ab5c-11e9-99d6-8300cc5f97fc.png)

**Comment by pompecukor** [comment] 2019-07-21 00:24
Another interesting one. Here I think I was changing the Target temp to see if it help, then rebooting each time. That is where you see the drops in the graph, as the Cube rebooted.

![image](https://user-images.githubusercontent.com/31744367/61585564-88afaa00-ab5e-11e9-986e-e86d55a89b3e.png)

**Comment by tridge** [comment] 2019-07-27 02:32
@pompecukor can you re-test with the fix from Sid that has now been merged?

**Comment by pompecukor** [comment] 2019-07-27 05:27
Yes I will

**Comment by IamPete1** [comment] 2021-07-26 16:11
Sounds like this has been fixed

**Closed by IamPete1** 2021-07-26 16:11 UTC
