### ISSUE TITLE
Pi Compute Module 4 PPM Issue

### ISSUE THREAD

**Issue by AbhishekJoshi** [ArduPilot/ardupilot#19037] opened 2021-10-24 23:22 UTC
## Bug report

On Pi 4 Board, I can read PPM normally.

I have all sensors and PCA9685 running on breadboard + benchtop. I'm working on my own board/solution, so this issue is very strange, as Pi4, Pi Zero, things are working normally, but not on a Pi4 Compute Module. My RCInput_RPI.cpp is latest, unchanged. Any changes I have done in the code are not relevant (as I see same behavior with vanilla latest master)

On both Pi 4 and Pi4 CM4, I am able to see the horizon, accel/gyro is calibrated, and if I go nose down with the breadboard, the HUD moves accurately.

However, On Pi 4 CM4, with same setup, I am unable to read PPM. Sometimes I see Pitch 3000 and other channels with 0. And other times, all channels with 0. 

I've confirmed both Pi4 and Compute Module 4  are running BCM2711, and Radio is bound, and wired to GPIO 4 as per the code.

I don't think this is a hardware issue as the hardware is theoretically compatible.

**Version**
Latest

**Platform**
[  ] All
[  ] AntennaTracker
[ X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Quad

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
Any linux hardware defined such that GPIO 4 is used for reading PPM

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by HefnySco** [comment] 2021-12-15 23:20
The issue was due to ardupilot could not detect RPI-CM4 and reports it as RPI-zero which corrupted DMA & PCM initialization in RCInput_RPI.cpp

**Comment by rmackay9** [comment] 2021-12-15 23:31
@HefnySco, I guess the issue is still open or can it be closed?

**Comment by HefnySco** [comment] 2021-12-15 23:34
@rmackay9  I am communicating with the owner of this issue to confirm from his side. for me it is working on my HW right now.

**Comment by HefnySco** [comment] 2022-01-11 18:59
@AbhishekJoshi I will close this now. please reopen if necessary.

**Closed by HefnySco** 2022-01-11 18:59 UTC
Labels: BUG, Linux
