### ISSUE TITLE
COMPASS2_ORIENT apparently ignored

### ISSUE THREAD

**Issue by arikrupnik** [ArduPilot/ardupilot#15711] opened 2020-11-02 21:08 UTC
## Bug report

**Issue details**

_Please describe the problem_

I have a an external GPS/compass unit that is mounted at 90 degree CCW offset from its nominal orientation. Changing the value of `COMPASS2_ORIENT` parameter seems to have no visible effect on compass readings. They are 90 degrees off. The FC (PH4m) has an onboard compass (in default orientation). With both compasses enabled, I get correct headings. But if I disable the first (built-in) compass, I get readings that are off by 90 degrees.

There's some discussion of the issue on the forum: https://discuss.ardupilot.org/t/compass2-orient-6-yaw270/63576

Photo of the installation:
![compass2_orient](https://user-images.githubusercontent.com/1756197/97919062-c9641000-1d1c-11eb-9f6a-f663df1b1001.png)

**Version**
_What version was the issue encountered with_
Plane 4.0.6 

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Eflite Scimitar; flying wing

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
Holybro PixHawk 4 Mini; mRo compass/GPS unit

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by arikrupnik** [comment] 2020-11-02 21:10
I should add that I tried changing `COMPASS2_ORIENT` to every single value and power-cycle the AP after each value write. I get the same readings regardless of the value.

**Comment by rmackay9** [comment] 2020-11-02 23:22
It's likely that the COMPASS2_EXTERNAL = 0.  The orientation aren't applied for internal compasses.  It would be good to confirm 100% that the 2nd compass is actually the external compass that you think it is.

**Comment by rmackay9** [comment] 2020-11-02 23:22
I'm going to close this because it's really a support issue and should be raised in the forums first, confirmed to be a bug or enhancement and then raised here.  Thanks for the report though.

**Closed by rmackay9** 2020-11-02 23:22 UTC

**Comment by arikrupnik** [comment] 2020-11-03 00:58
> It's likely that the COMPASS2_EXTERNAL = 0. The orientation isn't applied to internal compasses. It would be good to confirm 100% that the 2nd compass is actually the external compass that you think it is.

Thank you for for following up, @rmackay9 . If this is a support issue, perhaps I can impose on you to weigh in on my forum thread.

COMPASS2 is set as external. Here's a screenshot from the thread:

![](https://discuss.ardupilot.org/uploads/default/original/3X/6/7/6712f87ada5ce84de41df82495f49922fa91631f.png)
