### ISSUE TITLE
Builds are generating object files in working directory

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#2417] opened 2015-06-15 06:09 UTC
Since the recent PX4 merge a "make px4-v2" will dump object files (*.o and *.d) into the working directory which makes things quite messy. They should go into /obj or /temp or somewhere other than the working directory and also be cleaned correctly.

**Comment by lucasdemarchi** [comment] 2015-06-15 17:46
@magicrub what does "quite messy" look like?

**Comment by magicrub** [comment] 2015-06-15 17:49
my /ArduPlane folder triples in file count with every .cpp file now having a .cpp.d and .cpp.o file which then refreshes my eclipse folder browser. Also, searches done in Eclipse now include those files.

**Comment by lucasdemarchi** [comment] 2015-06-15 18:30
@magicrub ok, makes sense.

**Comment by magicrub** [comment] 2015-12-08 19:50
@guludo is this something in your realm of expertise?

**Comment by lucasdemarchi** [comment] 2015-12-08 20:19
@magicrub this is caused by PX4's build system.  It will eventually go away when waf is driving the PX4 build through its cmake integration.

**Comment by lucasdemarchi** [comment] 2015-12-08 20:22
@magicrub meanwhile you could also add exclusion filters in eclipse so it doesn't look for these files in the browser or search

**Comment by magicrub** [comment] 2015-12-08 20:38
Got it, thanks.

**Comment by guludo** [comment] 2015-12-09 15:36
@magicrub, sorry for the delayed answer. But as @lucasdemarchi said, that should be fixed when PX4 build is integrated in waf. :-)

**Comment by OXINARF** [comment] 2017-06-04 02:25
@magicrub Do you still want this open? waf build system uses a build folder for all produced files, but Make still pollutes the source dir.

**Comment by magicrub** [comment] 2017-06-04 04:37
This should stay open as long as we support make

**Comment by khancyr** [comment] 2019-04-05 08:34
make isn't support anymore, closing

**Closed by khancyr** 2019-04-05 08:34 UTC
Labels: BUG, BuildSystem, NeedAnswer
