### ISSUE TITLE
Issues with I2C airspeed on omnibus f4 pro

### ISSUE THREAD

**Issue by bobertholomew** [ArduPilot/ardupilot#16747] opened 2021-02-26 09:24 UTC
I'm running Plane 4.0.9 on an omnibus f4 pro

ARSPD_USE is set to 1 for enable, 
ARSPD_TYPE is set to 1 as I am using the i2c 4525 sensor
ARSPD pin is set to  pix hawk i2c or 65, although I have tried setting it to 1-20 with no luck

I have pull up resistors installed, so I'm not sure where to go from here, please help, thank you.

**Comment by amilcarlucas** [comment] 2021-02-26 18:00
This is probably not a bug, so please post support questions on the forum. This is for confirmed software bugs and feature requests. The forum has a lot more users that can help you out. closing this now.

**Closed by amilcarlucas** 2021-02-26 18:00 UTC

**Comment by bobertholomew** [comment] 2021-02-27 03:50
I think it probably is a bug. Everything is set up the way it should be, so it should work, but it doesn't.
