### ISSUE TITLE
Copter: LOITER_TURNS mission command moves to random position on circle radius

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#11192] opened 2019-04-25 06:16 UTC
To recreate the issue in SITL do this:

- create a mission like shown below with a LOITER_TURNS command with no lat/lon specified

![loiter-turns-mission](https://user-images.githubusercontent.com/1498098/56713979-50bae580-676e-11e9-9eee-19ccf654084d.png)

- arm the vehicle in Loiter ("arm throttle")
- switch to Auto and raise throttle ("AUTO", "rc 3 1100")
- the vehicle will move to some point on the circle
- stop and restart the simulation and repeat the steps above
- the vehicle will move to a different point on the circle

![loiter-turns-random-start-position](https://user-images.githubusercontent.com/1498098/56713590-0a18bb80-676d-11e9-8033-234c3c6ac489.png)

**Comment by rmackay9** [comment] 2019-04-25 06:30
I think the issue starts in the [mode_auto.cpp's do_circle method](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/mode_auto.cpp#L1199).  the circle_center is being set to the vehicle's current location which is fine but then within [AC_Circle library's init function](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AC_WPNav/AC_Circle.cpp#L52) (there are two) we should be calling init_start_angle(true);

**Comment by brotherlymite** [comment] 2019-12-24 07:54
Sorry but I'm still a bit confused on what exactly the problem is....
Is it something like when it starts to go to circle around its home position (As not lat/log is provided in LOITER_TURNS) it starts from a different position (or angle) on every try and we want it to start or move from a specific angle or something?

1st RUN
![Screenshot (4)](https://user-images.githubusercontent.com/22850280/71401504-159be980-2650-11ea-93d5-65de8b03f98c.png)

2nd RUN
![Screenshot (7)](https://user-images.githubusercontent.com/22850280/71401583-53990d80-2650-11ea-828a-862a304b1e21.png)

In the second run it started and ended from a different angle than the previous one

**Comment by brotherlymite** [comment] 2019-12-25 06:56
@rmackay9 Is what I'm thinking correct so I can try to fix this issue?

**Comment by YuxinPan** [comment] 2024-08-01 04:11
No longer able to reproduce as of ArduCopter 4.6-dev (see the 2 attempts in the attached video, in both cases the vehicle did not deviate).

I believe I have followed the same mission set up and SITL commands in my attempt.

Perhaps this issue has been unknowingly fixed in the last 5 years? @peterbarker what do you think?


https://github.com/user-attachments/assets/02199de9-b11c-4c54-a443-203c6f24a257


https://github.com/user-attachments/assets/876ef901-2a4f-45b0-a68b-c48bd25f5651

**Comment by peterbarker** [comment] 2024-08-01 11:02
Thanks @YuxinPan - from Discord:
![image](https://github.com/user-attachments/assets/69c2056c-78c0-4f1c-96f0-c6aaacb08b6e)

Closing this now - many thanks for re-testing!

**Closed by peterbarker** 2024-08-01 11:02 UTC
Labels: BUG, Copter, good first issue
