### ISSUE TITLE
Allow downloading CAM message from DF log over MAVLink

### ISSUE THREAD

**Issue by korgan** [ArduPilot/ardupilot#1978] opened 2015-03-13 07:19 UTC
**Summary**
It would be of great help if it was possible to just download the CAM parts of a log over MAVLINK. Typically after an imaging flight, we do not want to download the whole flight log which is just stored to debug if we were to crash but only the parts which contain CAM datapoints for the georeferencing of images.

**Description**
The current situation: We are capturing images using an Ardupilot and either CAM_TRIGG_DIST or DO_DIGICAM_CONTROL waypoints which stores image coordinates in the log. To improve the postprocessing we are georeferencing the images using said log.

Now the problem is that our flights sometimes take over an hour and the log grows to a size where it is just impractical to download it over Mavlink because it just takes a very long time, sometimes more than the actual flight. We are currently logging a lot of variables just to make sure that in the event of a crash we can figure out exactly what was going on.
It would be a great help, not only to us I think but to a lot of other people who do mapping flights, if there was some kind of method to just download the CAM parts as a whole without any other information.

**Comment by WickedShell** [comment] 2018-06-25 09:16
Closing in favor of #3187 which has more detail/proposed solution (even though it's technically a duplicate of this issue)

**Closed by WickedShell** 2018-06-25 09:16 UTC
Labels: Enhancement, Library
