### ISSUE TITLE
AP_RangeFinder: RNGFND1_OFFSET value is ignored

### ISSUE THREAD

**Issue by mtbsteve** [ArduPilot/ardupilot#13252] opened 2020-01-13 10:38 UTC
**Bug report**

**Issue details**
With AC 4.0 the parameter RNGFND1_OFFSET is being ignored. I am using a LidarLite connected via PWM. It works well with Arducopter 3.6 all versions with the NuttX core.

_Please describe the problem_
Here are 2 screenshots of the rangefinder output, the first one with AC 3.6 with the correct altitude and RNGFND_OFFSET=-20 
![AC3 6 12_Rangefinder_PWM](https://user-images.githubusercontent.com/11302624/72249019-cca8d680-35f8-11ea-89ee-635b7826c58e.PNG)

and the second screenshot with AC 4.0.1 RC2 and RNGFND1_OFFSET set to -20.
Whatever I enter is ignored. Seems like its being missed after renaming of the parameters in AC 4.
![AC4 0 1RC2_Rangefinder_PWM](https://user-images.githubusercontent.com/11302624/72249177-1b567080-35f9-11ea-9cdb-f2a57cb0e92a.PNG)

Another observation is the voltage, with AC 3.6 the voltage is displayed, with AC4 there is no reading.

**Version**
_What version was the issue encountered with_
AC 4.0.1 RC2, AC 4.0.0

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Quad
**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
Cube green
**Logs**
_Please provide a link to any relevant logs that show the issue_
[https://1drv.ms/u/s!AnKeW8KMoCcyhiMb9kF6WwfbQgGA?e=sqpNtV](url)

**Comment by rmackay9** [comment] 2020-01-16 02:30
I've confirmed the issue and it seems to be that this is a regression from Copter-3.6.x.

In fact, this parameter is not used by the majority of drivers.  In Copter-4.0 only the analog driver uses it.  In Copter-3.6 it was the analog driver and the PWM driver that used it.

I think we should fix this in two steps:

1. restore the PWM driver's use of this parameter
2. add the use of this parameter to all other drivers

This report was also raised in [this discussion](https://discuss.ardupilot.org/t/rngfnd1-offset-not-working-for-pwm-and-i2c-lidarlite/51125)

**Comment by rmackay9** [comment] 2020-02-01 00:40
This is fixed for the PWM range finders and is [included in Copter-4.0.2-rc1](https://discuss.ardupilot.org/t/copter-4-0-2-rc1-available-for-beta-testing/51790) so I'll close it here.  Thanks!

**Closed by rmackay9** 2020-02-01 00:40 UTC
Labels: BUG, Copter, Enhancement
