### ISSUE TITLE
Airspeed error units incorrect

### ISSUE THREAD

**Issue by dongfang** [ArduPilot/ardupilot#335] opened 2013-06-03 19:23 UTC
According to MAVLink 

typedef struct __mavlink_nav_controller_output_t
{
... float aspd_error; ///< Current airspeed error in meters/second
...
}
airspeed error unit should be m/s

However in ArduPlane
static void NOINLINE send_nav_controller_output(mavlink_channel_t chan)
{
    mavlink_msg_nav_controller_output_send(
...        airspeed_error_cm,
}

it is cm/s.

**Comment by gmorph** [comment] 2015-09-04 03:15
The MAVLink specification states it should be in meters/second.  The problem is if we change this we need to co-ordinate with all the GCS's so they make the corresponding update.  For the moment this is going in the too much effort for too little gain box.
Thanks, Grant.

**Comment by WickedShell** [comment] 2015-09-04 05:07
I've encountered a problem with a third party program that correctly
implemented MAVlink and they have good interoperability. I think it's worth
changing even though it's a headache for ground stations.

**Comment by magicrub** [comment] 2016-05-17 22:11
Airspeed error is now in m/s but the mavlink msg is still cm/s.
https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/GCS_Mavlink.cpp#L374

**Comment by WickedShell** [comment] 2016-05-17 22:26
It would be really nice to fix the message IMO. Even if it causes some GCS headache, makes us more compliant with the spec, and makes it easier for GCS's to support multiple platforms more easily.

**Comment by WickedShell** [comment] 2017-11-03 09:02
I think for GCS historical compatibility reasons we won't ever be able to fix this. Closing it as such, and because there hasn't been any traction on actually making the change. (Happy to have the unit fixed that we send, but I've meet a *lot* of resistance last time I tried to push it)

**Closed by WickedShell** 2017-11-03 09:02 UTC
Labels: BUG, MAVLink, Plane

**Comment by MishkaRogachev** [comment] 2018-03-22 15:08
I'm developing new [GCS](https://github.com/MishkaRogachev/JAGCS). Should i follow MavLink or use cm/s too?
