### ISSUE TITLE
Richen Power Generator's Driver can't be enabled

### ISSUE THREAD

**Issue by Tabocim** [ArduPilot/ardupilot#22368] opened 2022-12-09 08:19 UTC
**Issue details**
**_Bug:_** Richen Power Generator's Driver can't be enabled

In this file /[libraries](https://github.com/ArduPilot/ardupilot/tree/master/libraries)/[AP_Generator](https://github.com/ArduPilot/ardupilot/tree/master/libraries/AP_Generator)/AP_Generator.cpp
line 77
![image](https://user-images.githubusercontent.com/35541048/206655505-b602362c-9ee6-46c4-852b-0274e6cda609.png)

The Richen Power generator's driver will not be loaded because of this bug 

in this file /[libraries](https://github.com/ArduPilot/ardupilot/tree/master/libraries)/[AP_Generator](https://github.com/ArduPilot/ardupilot/tree/master/libraries/AP_Generator)/AP_Generator_RichenPower.h
line 7 
![image](https://user-images.githubusercontent.com/35541048/206655644-c3d35c14-e2d7-41ee-accb-c40577e65876.png)

**it should be #define AP_GENERATOR_RICHENPOWER_ENABLED 1**

**Since Version**
4.3.0

**Airframe type**
All

**Hardware type**
All

**Comment by auturgy** [comment] 2023-08-12 03:08
I'm going to close this, as having the driver excluded by default is the intended behaviour.

**Closed** 2023-08-12 03:08 UTC
