### ISSUE TITLE
Copter: Splinewaypoint skips ahead on mode change, then AUTO resume

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot#8538] opened 2018-05-30 21:01 UTC
#### Issue details
When next wp is a splineWP, it will be skipped on auto resume.
This is potentially dangerous if there is an obstruction in the "shortcut" path.

#### Version
AC3.6.RC1 and older AC

This video illustrate it perfectly: https://www.youtube.com/watch?v=v6GIQwG1rlE
Flying a box, when AC mode is temporarily changed, then back to AUTO, the current WP will be skipped.

**Comment by rmackay9** [comment] 2018-05-31 00:44
well, that's unexpected!  thanks for the report!

**Comment by AndKe** [comment] 2018-05-31 10:40
I tried to solve it and push a PR at the same time, but had to give up as I failed to find the reason within reasonable time. :)

**Comment by khancyr** [comment] 2018-05-31 12:27
@rmackay9, I suspect this is the behavior caused by : https://github.com/ArduPilot/ardupilot/issues/6798

**Comment by rmackay9** [comment] 2018-05-31 13:00
@khancyr, OK thanks.  If that's the case then it should be fixed in master (and Copter-3.6)..

**Comment by khancyr** [comment] 2018-05-31 13:30
@rmackay9 I mean the patch skip the first spline waypoint is case two waypoints are too close, 
 // if target velocity is zero the origin and destination must be the same
// so flag reached destination (and protect against divide by zero)
I may explain the problem here

**Comment by IamPete1** [comment] 2021-08-30 23:06
I cant reproduce on master, I suspect this was fixed with all the SCurve changes.

**Closed by IamPete1** 2021-08-30 23:06 UTC
Labels: BUG, Copter
