### ISSUE TITLE
Roll/pitch rate PID value have a lower bound of 0.08

### ISSUE THREAD

**Issue by fantasycenturay** [ArduPilot/ardupilot#7212] opened 2017-11-09 16:54 UTC
#### Issue details
I use a pixracer on a qavr 210 frame. The quad flies pretty well at Roll rate P=0.02. But I cannot write that using mission planner. There's a lower bound of 0.08. And at 0.08, the quad shakes pretty badly.

#### Version
arducopter v3.5.3

#### Platform
Copter

#### Airframe type
X4

#### Hardware type
pixracer

#### Logs
Open mission planner and connect to a pixracer or pixhawk running copter v3.5.3, at extended tuning page, enter any value below 0.08 into the roll/pitch rate P value. You will see that won't work.

**Comment by OXINARF** [comment] 2017-11-12 03:05
Reading from the forum looks like this was fixed by the user.

This issues list is for feature requests and confirmed bugs. For user support please always post in the forum (http://discuss.ardupilot.org).

**Closed by OXINARF** 2017-11-12 03:05 UTC
