### ISSUE TITLE
Auto Drift mode

### ISSUE THREAD

**Issue by raptortrias** [ArduPilot/ardupilot#6054] opened 2017-04-15 14:40 UTC
#### Issue details
Is it possible to setup Waypoint flight in Drift mode for arducopter.
This is for a hybrid QUAD with lifting surface that extends endurance for mapping missions.

#### Version
Any

#### Platform
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover

#### Airframe type
QUAD

#### Hardware type
Pixhawk 1/2

#### Logs
NA

**Comment by rmackay9** [comment] 2017-04-17 22:44
I guess what you're looking for is to make sure the vehicle always points forward?  The issue is that sometimes the vehicle points towards the next waypoint and ends up flying slightly sideways?

If this is the case, in the short-term you can set the WP_YAW_BEHAVE to "3" which is to point in the direction the GPS indicates we are travelling.  This is what most helicopter users use I think.

There is also an issue raised somewhere here to address the issue of the vehicle pointing to the next waypoint "too early".  There is a good reason why it does that (i.e. it's not a bug so to speak) but we can improve it.

**Comment by raptortrias** [comment] 2017-04-18 08:50
Hi Randy,

 Thanks for suggestion, the issue is not only the YAW behaviour, the issue is that I require the copter to keep flying forwards at speed. So for example in WP mission once a WP is reached copter will YAW and flying to next waypoint. What I require is that the actual flight path resembles that of fixed wing, because if we loose airspeed and stop direction abruptly for yaw the flying surface will stall abruptly.

 Thanks

**Comment by rmackay9** [comment] 2017-04-18 12:08
Ok, I see.  Have you tried Spline waypoints?

**Comment by lthall** [comment] 2018-01-12 00:57
Issue can be solved using existing functionality. Planed functionality will further improve this so I am closing it.

**Closed by lthall** 2018-01-12 00:57 UTC
Labels: Copter, NeedAnswer
