### ISSUE TITLE
Rover: add mechanical brake support in rover 

### ISSUE THREAD

**Issue by stevefoxuk** [ArduPilot/ardupilot#18678] opened 2021-09-16 02:34 UTC
Rover does not support a mechanical brake, this means vehicles running an IC engine have no braking option and electric vehicles which have a mechanical brake cannot make use of it.

Please add support for braking , I know others would like to see this feature too.

**Comment by rmackay9** [comment] 2021-09-16 03:50
This is a duplicate of https://github.com/ArduPilot/ardupilot/issues/7040 so I will close this one as is our normal practice (oldest one remains)

**Closed by rmackay9** 2021-09-16 03:50 UTC
Labels: Enhancement, Rover
