### ISSUE TITLE
Send all RC OUTPUTS to GCS (i.e. channels above 8)

### ISSUE THREAD

**Issue by GrahamDyer** [ArduPilot/ardupilot#1968] opened 2015-03-11 15:36 UTC
MP Issue #812 refers

The Pixhawk supports outputs to more than 8 channels but ever since APM2.x days the MP has always only shown ch 1-8 outputs. Please can the outputs to the additional channels (9-12) be shown in Status?

![channels](https://cloud.githubusercontent.com/assets/3287001/6599899/06aeefc4-c815-11e4-8c11-19c64fa0fe0b.GIF)

**Comment by JSGordon** [comment] 2015-03-14 08:20
This would enhance realtime troubleshooting on these channels.   I could have used this feature a number of times working on setups where we are using channels 9-12.

**Comment by tridge** [comment] 2015-03-14 09:17
When there are more than 8 input channels ArduPilot will send the RC_CHANNELS message with up to 16 channels. That is in all current releases. The problem is that MissionPlanner doesn't display it.
Please open an issue with MissionPlanner.

**Comment by GrahamDyer** [comment] 2015-03-15 13:21
https://github.com/diydrones/MissionPlanner/issues/812

**Comment by rmackay9** [comment] 2015-03-16 02:12
re-opening because although rc-inputs are covered, rc-outputs are not.

**Comment by R-Lefebvre** [comment] 2015-12-22 18:17
Attempt at fixing this is in here:

https://github.com/R-Lefebvre/ardupilot/commits/MAVlink_Servo_Output_WIP

However, this breaks MP, so new issue created:

https://github.com/diydrones/MissionPlanner/issues/1090

**Comment by WickedShell** [comment] 2016-09-06 08:01
This was addressed in 306487c (only I have misinterpreted either the issue or the commit).

**Closed by WickedShell** 2016-09-06 08:01 UTC
