### ISSUE TITLE
Copter: allow pilot to forcibly retake control from GCS with TX

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1372] opened 2014-09-08 14:02 UTC
If someone is flying with a joystick or GCS's virtual sticks, it would be good to allow the pilot to forcibly retake control from the GCS by flicking a switch (flight mode?  ch7/ch8?) on the TX.  It's possible at the moment for the GCS to release control by setting all overrides to zero and even disconnecting the GCS from the radio should cause a GCS failsafe and result in the controls going back to the transmitter but these are slightly rough solutions.

When something goes wrong, it would probably be best for the pilot to be able to reach for the TX, click a switch and be back in control.

**Comment by R-Lefebvre** [comment] 2015-01-01 02:10
Perhaps if RC Input Ch5 changes, it should reset RC_Override?  Is it a fair assumption the pilot is attempting to retake manual control?

**Comment by rmackay9** [comment] 2015-01-02 11:54
@R-Lefebvre, yes sounds like a good idea.  We should probably never allow the GCS to override the flight mode channel.

**Comment by hotelzululima** [comment] 2015-03-07 10:14
ah I will respectfully disagree here.. please see this posting http://diydrones.com/forum/topics/arducopter-3-2-1-beta-testing?id=705844%3ATopic%3A1882038&page=27#comments

everything was fine until a comms error occurred on the RC xmitter which had been left sitting on the side and the mode for the apm went stab at zero throttle(which the rc xmitter had to be for arming) the GCS was in home->landing mode when this occurred.. so from the viewpoint of APM being flown from a tablet with the RCTX being left as a backup control and allowing that to happen IN FLIGHT on arducopter doesnt work to avoid crashes..

ie this safety feature as presently implemented is causing crashes dues to a lack of safety interlocks.

        hzl

**Comment by R-Lefebvre** [comment] 2015-03-07 13:16
HZL, I understand your frustration.  This is not such an easy problem to solve without creating other problems elsewhere.  I'm pretty much out of ideas at this point.  As you may know, I'm not a fan of anything that removes an operator's ability to reliably stop the propellers quickly.

I look forward to whatever logical suggestions you can have.

**Comment by hotelzululima** [comment] 2015-03-07 18:47
Rob.. get this carefully.. this is NOT safety shaming..
 the craft IRIS+ is targeted at the RTF market,
 to point at a throttle FS that was NOT set as part of normal IRIS parameters is to announce that your product is NOT setup for RTF usage by new pilots ,
and the interface for flight safety is inserted in the 

AND to expect pilots to be experienced enough on your interface to be able to set before there was a problem?


The RCTX got a comms error and reset  the commanded flight mode while the tablet GCS was in control.. that is a failure of preemption in the design.

I hear the frustration of all the folks here with finding a solution to the issue to spinning props vs failing copters.. the important issue to remember here is copters have less than ZERO glide ratio

The best that can be managed is a ballistic trajectory.. not good..

and if such a failsafe is critical to NOT crashing it should be insured in the FC itself not in the RC/TX or the GCS.. they are too far separated from the issue in the design to be effective as a fix.

And again.. a CRASHME switch is what the effect of a throttle cut  switch for a copter is,
NOT good for a product sold and advertised to the public as RTF(IRIS).

Personally I have the same fear of a throttle cut switch on a unmanned copter as I would aboard a manned aircraft with a switch that instantly shut the main blade down from spinning.

Nothing which allows that UAV to stop midair and fall is appropriate from a flight safety perspective.
that's NOT only FAA thinking.. its product safety issues here in California and the fact that NOTHING releases a manufacturer under civil law from lawsuits caused by torts committed by a faulty design to third parties(only firearms manufacturers have that freedom from civil suit under law for product safety complaints and its NOT a complete release.. defective products causing harm they are still liable for.. 

   
      Switches into Stab mode with Throttle = zero  without safety interlocks  for any reason is a product safety complaint waiting to happen and a BIG RED FLAG for insurance company actuarial's.


     hzl
ps insurance requirements will drive commercial deployment of UAV copters.

**Comment by lthall** [comment] 2015-03-07 23:39
Hi Randy,

The current assumption Arducopter works on is that the RC transmitter is the primary control and all other methods of control are secondary. We could implement a ch7 or ch8 switch that is used to define that we are not operating the RC transmitter and are instead operating from the GCS. This could then be used to ensure we enter Loiter, RTL or Land (or what ever we think is appropriate) if we loose GCS (or switch back from the GCS). The RC transmitter operator can then take control at any time by flicking that Ch7/8 switch back to RC control.


Hi hotelzululima,

As far as I know, all regulations regarding the flight of copters both in a hobby club and commercially explicitly say you are not allowed to fly over property and people (using terms loosely here). Therefore it is 'safe' for a copter to cut the throttle and let it 'crash' along a ballistic path, as this should be clear.

This is why CRASHME switches are mandatory when flying in many instances, and are a powerful feature to get permission from body's like the FAA to fly in more risky environments (Like in an airport for example). This feature is also helpful to convince insurance companies to give you coverage.

As for the RTF market, if an RTF manufacture chooses to omit or neglect a feature, then that is up to them and you should discuss it directly with the manufacture of that copter. The devs have always claimed the RC transmitter is the primary control and have been very concerned with the issues using other means of control.

The thing that frustrates me most about these conversations is there has is rarely a thorough analysis of the problem. The truth is we need to start developing a full matrix of control methods and issues so that we can examine ALL the interactions to ensure there are appropriate safety mechanisms and blocks in place in each instance.

**Comment by R-Lefebvre** [comment] 2015-03-08 00:19
To me, this issue is very clear.

The #1 consideration in regards to safety, is preventing and/or minimizing injury to humans.  Protecting the unmanned aircraft from impact with the ground is absolutely secondary to that.

There are basically 3 main vectors by which UAV's can injure people.

#1) Direct high speed impact from above, due to a fall from altitude

#2) Direct high speed impact horizontally, due to flying at speed

#3) Propeller injury

#1 is a big problem particularly for multirotors.  There are many reasons they could fall.  As HZL stated, they have no glide slope.  If the motors are stopped by the controller, or one or more motors fail, or the battery fails, or the flight controller fails, they plummet.  This is why it is strongly recommended, if not a firm requirement, to NEVER EVER fly them overhead of people.  This is a requirement for both voluntary hobby organizations, as well as government aircraft regulations.  

There is a big difference here between manned and unmanned aviation.  As HZL states, there is no "blade ejection" button for a helicopter, or anything that would force it to plummet.  This is because there are humans IN the aircraft, and impact with the ground would injure them.  There are no regulations preventing aircraft from flying overhead people.  It happens every day in major cities around the world.  The aircraft are designed to such high engineering standards, that the odds of collision with people on the ground are extremely low.  The primary concern is injury to people in the aircraft.

Conversely, nobody really cares if your UAV impacts the ground, other than the owner who suffers financial loss.  Also, UAV's are not engineered anywhere near as well at manned aircraft.  They fall out of the sky all the time.  This is why regulations are in place to prevent operation overhead of, or really anywhere near humans, other than people involved in the operations.

For these reasons, accidental power cut-off, is not a concern for regulators.  There are already many rules for UAV's in many jurisdictions, and not a single one that I'm aware of contains statements about preventing loss of power.

In fact, many jurisdictions specifically REQUIRE methods to cut power.  Furthermore, some even require automatic power-cut methods.  Italy is one example, which absolutely requires all commercial UAV's to employ Flight Termination systems.  At the OBC in Australia, systems were required to have Automatic Flight Termination systems.  This would cut power to a multirotor, or cause an airplane to flat-spin into the ground (not merely cutting power and letting it glide, but flat-spin it in.

#2) is less of a concern for multirotors, as they typically are not used for high speed flight.  Also, it is very easy to stop them from moving.  They can be stopped under thrust control (unlike and airplane).  Or power can be cut, and they follow ballistic trajectory which will have them safely impact the ground if they have been flown in a safe location.  While many of the automatic flight control systems may fail, causing a multirotor to veer off in an unintended direction, if we maintain the ability to cut power quickly, this is how we maintain safety against this vector.

#3) This is without doubt, the leading cause of injury from multirotors.  Unintended throttle ups, or low-speed collisions either horizontally or from above which are primarily due to neglecting #1.  Whatever the cause of the accident in this case, the most important thing we must do to lessen the severity of the injuries, is to cut power to the motors as fast as possible.  

Currently, the fastest, and most direct way to kill power to the motors of an Arducopter controlled aircraft, is to switch to Acro or Stabilize, and drop the throttle.  Due to the already high incidence of these type of injuries, and this being our only mechanism to stop the motors, there is absolutely no willingness amongst the primary developer group to remove, limit, or delay this functionality.

Period.

Now, this being an open source project, if a person REALLY wants to do this, they are free to modify the code as they see fit.  That's the beauty of open source.  Even though this would be ill-advised, and probably illegal in most jurisdictions, that is up to the individual responsible.  Leonard, myself, and I believe Randy are not at all interested in doing this in the released firmwares.

**Comment by ionoy** [comment] 2015-04-14 12:02
We have actually implemented this feature in our system. We use channel 8 like "when ch8 > 1900 stop applying overrides". Would be great to have this feature already implemented natively.

**Comment by R-Lefebvre** [comment] 2015-04-14 16:18
Sorry, which system?  And, you pass through incoming RC Inputs to the motors on a quadcopter?  Must be hard to fly?

**Comment by ionoy** [comment] 2015-04-14 17:25
We have both our own GCS software and quad platform based on Arducopter. As we usually fly beyond line of sight we use autopilot controlled modes: Auto, Loiter and Guided. RC is only for emergency situations, when quad is nearby. Otherwise it would even be able to reach our flying platform.

**Comment by R-Lefebvre** [comment] 2015-04-14 18:40
I'm not following then.  What exactly are you doing?  How is "stop applying overrides" different than Stabilize mode?

**Comment by ionoy** [comment] 2015-04-15 06:19
We fly exclusively by overriding RC input with mavlink packets. If something extraordinary happens and pilot needs to regain control, he can turn on his transmitter and set channel 8 to 2000 by flipping the switch. This means, that autopilot now ignores override values and only listens to RC receiver input.

**Comment by R-Lefebvre** [comment] 2015-04-15 11:22
Ah, I see now.  Ok, we can consider something like this.

**Comment by R-Lefebvre** [comment] 2015-11-13 23:44
Randy, I had mentioned this the other day.  Thinking that Input Manager can help solve this.  Maybe create a parameter which the user sets to determine which input method is "King".  It would default to be RC Tx (PWM/SBUS).  Then the user would have to flip a switch, to relinquish control to the GCS (RC Overrides).  This makes it a very deliberate action. Unfortunately it eats up a channel.  But I really can't figure out any other way to handle this.

**Comment by rmackay9** [comment] 2015-11-14 02:20
@R-Lefebvre, yes, I agree the input manager is the right place to do this.  I'm not sure we should be doing any work involving rc-overrides though 'cuz I think that's not the way we should be getting commands from the GCS even if they're manual commands.  We should use that manual-control mavlink message instead.  Once we have support for that, then it makes sense to record which is "king".  I don't hear many complaints from people who are trying to use two controllers though.. do you?

**Comment by r4space** [comment] 2017-06-16 17:24
Hi,  

Sorry I know this is a very OLD thread but  couldn't find any other documentation on this concept.  How was this resolved in the end?  i.e what is the behavior now?  @R-Lefebvre, did some form of @ionoy 's approach get implemented natively, can I assign CH8 to a switch and stop all overrides either via a configuration parameter somewhere in mission planner maybe or via a dronekit command now?

I can implement this myself if I need to but was obviously just wondering if someone else had already done so publicly?

**Comment by OXINARF** [comment] 2017-06-16 19:42
@r4space This is still open... It wasn't solved.

**Comment by rmackay9** [comment] 2017-06-17 01:03
In practice it really hasn't been a problem.  the joystick commands (received by the autopilot as "rc-overrides") can be stopped from the ground station and if the ground station crashes then control is handed back to the transmitter.  So really.. I personally haven't heard users complain about this issue.. even though there are some users that use joysticks to control their vehicles much of the time.

**Closed** 2018-01-11 07:24 UTC
Labels: Copter, Safety

**Comment by lthall** [comment] 2018-01-11 07:25
open again if necessary.
