### ISSUE TITLE
Q_P_ Parameters have double underscore in wiki and maybe elswhere _ _

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#10046] opened 2018-12-18 01:09 UTC
### Bug report

**Issue details**

_Please describe the problem_
![image](https://user-images.githubusercontent.com/35429159/50125584-2b9def80-022f-11e9-825e-2ac43f7f6363.png)

**Version**
Master

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quadplane

**Comment by rmackay9** [comment] 2018-12-18 01:18
[The issue is here I think](https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/quadplane.cpp#L36).  We need to replace "P_" with just "P".

**Comment by rmackay9** [comment] 2018-12-18 04:53
I've got a [fix here that I will PR shortly](https://github.com/rmackay9/rmackay9-ardupilot/commits/quadplane-doc-fix).

**Comment by OXINARF** [comment] 2018-12-18 12:01
Fixed by #10049.

**Closed by OXINARF** 2018-12-18 12:01 UTC
